#include <lumino_core/graphics/Material.hpp>
#include <lumino_core/graphics/GraphicsContext.hpp>
#include <lumino_core/graphics/TextureLoader.hpp>
#include <lumino_shader/UnifiedShader2.hpp>
#include <lumino_shader/UnifiedShaderSerializer2.hpp>
#include <cstring>

// Precompiled shader data (generated by luminosc during build).
// These are hex-array .inl files included as static byte arrays.
static const unsigned char s_unlitShaderData[] = {
#include "shaders/Unlit.lcsh.inl"
};

static const unsigned char s_basicLitShaderData[] = {
#include "shaders/BasicLit.lcsh.inl"
};

namespace ln {

// ─── Helpers ─────────────────────────────────────────────────────────────

static rhi::BindingType mapElementKind(shader::ParameterBlockElementKind kind) {
    switch (kind) {
    case shader::ParameterBlockElementKind_ConstantBuffer: return rhi::BindingType::UniformBuffer;
    case shader::ParameterBlockElementKind_Texture:        return rhi::BindingType::SampledTexture;
    case shader::ParameterBlockElementKind_SamplerState:   return rhi::BindingType::Sampler;
    case shader::ParameterBlockElementKind_StorageBuffer:  return rhi::BindingType::StorageBuffer;
    default: return rhi::BindingType::UniformBuffer;
    }
}

static rhi::BindGroupLayoutDesc buildBindGroupLayoutFromReflection(
    const shader::ParameterBlockLayout2& block,
    const shader::TargetBindingLayout2& mergedBindings) {
    rhi::BindGroupLayoutDesc desc;
    for (const auto& binding : mergedBindings.bindings) {
        if (binding.setIndex != block.setIndex) continue;
        rhi::BindGroupLayoutEntry entry;
        entry.binding = binding.bindingIndex;
        entry.type = mapElementKind(binding.kind);
        entry.visibility = static_cast<rhi::ShaderStage>(binding.used);
        desc.entries.push_back(entry);
    }
    return desc;
}

static const shader::ParameterBlockLayout2* findParameterBlock(
    const shader::UnifiedShader2* shader, const std::string& name) {
    for (const auto& block : shader->parameterBlocks()) {
        if (block.name == name) return &block;
    }
    return nullptr;
}

static int16_t findConstantBufferSize(const shader::ParameterBlockLayout2& block) {
    if (block.hasImplicitConstantBuffer) {
        for (const auto& elem : block.elements) {
            if (elem.kind == shader::ParameterBlockElementKind_ConstantBuffer)
                return elem.constantBufferSize;
        }
    } else {
        for (const auto& elem : block.elements) {
            if (elem.kind == shader::ParameterBlockElementKind_ConstantBuffer)
                return elem.constantBufferSize;
        }
    }
    return -1;
}

// ─── Material ────────────────────────────────────────────────────────────

void Material::setColor(const Color& color) {
    baseColor_ = color;
    paramsDirty_ = true;
}

void Material::setTexture(rhi::Texture* texture) {
    if (texture) {
        texture->addRef();
        baseTexture_ = Ref<rhi::Texture>::adopt(texture);
    } else {
        baseTexture_.reset();
    }
    baseTextureView_.reset();
    paramsDirty_ = true;
}

void Material::setSpecular(const Color& color, f32 shininess) {
    specularColor_ = color;
    shininess_ = shininess;
    paramsDirty_ = true;
}

void Material::setBlendEnabled(bool enabled) { blendEnabled_ = enabled; }
void Material::setCullMode(rhi::CullMode mode) { cullMode_ = mode; }
void Material::setDepthTestEnabled(bool enabled) { depthTestEnabled_ = enabled; }
void Material::setDepthWriteEnabled(bool enabled) { depthWriteEnabled_ = enabled; }

Result<void> Material::updateBindGroup(rhi::Device* device) {
    if (!paramsDirty_) return {};

    // Update uniform buffer
    if (paramBuffer_) {
        void* mapped = paramBuffer_->map();
        if (mapped) {
            if (type_ == MaterialType::Unlit) {
                UnlitMaterialParamsUBO ubo;
                ubo.color[0] = baseColor_.r; ubo.color[1] = baseColor_.g;
                ubo.color[2] = baseColor_.b; ubo.color[3] = baseColor_.a;
                std::memcpy(mapped, &ubo, sizeof(ubo));
            } else {
                BasicLitMaterialParamsUBO ubo;
                ubo.color[0] = baseColor_.r; ubo.color[1] = baseColor_.g;
                ubo.color[2] = baseColor_.b; ubo.color[3] = baseColor_.a;
                ubo.specular[0] = specularColor_.r; ubo.specular[1] = specularColor_.g;
                ubo.specular[2] = specularColor_.b; ubo.specular[3] = shininess_;
                std::memcpy(mapped, &ubo, sizeof(ubo));
            }
            paramBuffer_->unmap();
        }
    }

    // Create texture view if missing
    if (baseTexture_ && !baseTextureView_) {
        auto tvResult = device->createTextureView(baseTexture_.get());
        if (!tvResult) return tl::make_unexpected(tvResult.error());
        baseTextureView_ = std::move(*tvResult);
    }

    // Create sampler if missing
    if (!sampler_) {
        rhi::SamplerDesc samplerDesc;
        auto sampResult = device->createSampler(samplerDesc);
        if (!sampResult) return tl::make_unexpected(sampResult.error());
        sampler_ = std::move(*sampResult);
    }

    // Recreate BindGroup with current parameters
    if (materialBindGroupLayout_ && baseTextureView_ && sampler_) {
        rhi::BindGroupDesc bgDesc;
        bgDesc.layout = materialBindGroupLayout_.get();
        bgDesc.entries = {
            {0, paramBuffer_.get(), 0, materialParamBufferSize_, nullptr, nullptr},  // uniform buffer
            {1, nullptr, 0, 0, baseTextureView_.get(), nullptr},      // texture
            {2, nullptr, 0, 0, nullptr, sampler_.get()},              // sampler
        };
        auto bgResult = device->createBindGroup(bgDesc);
        if (!bgResult) return tl::make_unexpected(bgResult.error());
        materialBindGroup_ = std::move(*bgResult);
    }

    paramsDirty_ = false;
    return {};
}

Result<void> Material::buildPipeline(
    rhi::Device* device,
    rhi::PipelineLayout* pipelineLayout,
    rhi::TextureFormat colorFormat,
    rhi::TextureFormat depthFormat,
    rhi::PrimitiveTopology topology) {

    rhi::RenderPipelineDesc rpDesc;
    rpDesc.layout = pipelineLayout;
    rpDesc.vertexShader = vertShader_.get();
    rpDesc.fragmentShader = fragShader_.get();
    rpDesc.vertexEntry = vertEntry_;
    rpDesc.fragmentEntry = fragEntry_;
    rpDesc.vertexBuffers = {standardVertexLayout()};
    rpDesc.topology = topology;
    rpDesc.cullMode = cullMode_;
    rpDesc.colorFormats = {colorFormat};
    rpDesc.depthStencilFormat = depthFormat;
    rpDesc.depthStencil.depthTestEnable = depthTestEnabled_;
    rpDesc.depthStencil.depthWriteEnable = depthWriteEnabled_;

    if (blendEnabled_) {
        rhi::BlendState bs;
        bs.enabled = true;
        bs.srcColor = rhi::BlendFactor::SrcAlpha;
        bs.dstColor = rhi::BlendFactor::OneMinusSrcAlpha;
        bs.colorOp = rhi::BlendOp::Add;
        bs.srcAlpha = rhi::BlendFactor::One;
        bs.dstAlpha = rhi::BlendFactor::OneMinusSrcAlpha;
        bs.alphaOp = rhi::BlendOp::Add;
        rpDesc.blendStates = {bs};
    }

    auto pipelineResult = device->createRenderPipeline(rpDesc);
    if (!pipelineResult) return tl::make_unexpected(pipelineResult.error());
    pipeline_ = std::move(*pipelineResult);
    return {};
}

// ─── Helper: load shaders from precompiled .lcsh data ────────────────────

Result<Ref<Material>> MaterialFactory::createMaterialFromShaderData(
    rhi::Device* device,
    rhi::PipelineLayout* pipelineLayout,
    rhi::TextureFormat colorFormat,
    rhi::TextureFormat depthFormat,
    const unsigned char* shaderData, size_t shaderDataSize,
    MaterialType type) {

    // Deserialize the unified shader from the binary blob.
    auto loadResult = shader::UnifiedShaderSerializer2::loadFromData(shaderData, shaderDataSize);
    if (!loadResult) return tl::make_unexpected(loadResult.error());
    auto unifiedShader = std::move(*loadResult);

    // Find the Forward pass for SPIR-V target.
    auto& globalPasses = unifiedShader->globalShaderPasses();
    if (globalPasses.empty()) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No shader passes found"});
    }

    auto* globalPass = globalPasses[0].get();
    auto targetPassId = globalPass->getTargetShaderPassId(shader::ShaderTarget_SPIRV);
    auto* targetPass = unifiedShader->targetShaderPass(targetPassId);
    if (!targetPass) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No SPIRV target pass"});
    }

    auto* vertEP = unifiedShader->targetEntryPoint(targetPass->vertEntryPointId);
    auto* fragEP = unifiedShader->targetEntryPoint(targetPass->fragEntryPointId);
    if (!vertEP || !fragEP) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "Missing entry points"});
    }

    auto* vertBlob = unifiedShader->blob(vertEP->codeBlobId);
    auto* fragBlob = unifiedShader->blob(fragEP->codeBlobId);

    // Create shader modules
    rhi::ShaderModuleDesc vsDesc;
    vsDesc.spirvCode = reinterpret_cast<const u32*>(vertBlob->data.data());
    vsDesc.spirvSizeBytes = vertBlob->data.size();
    auto vsResult = device->createShaderModule(vsDesc);
    if (!vsResult) return tl::make_unexpected(vsResult.error());

    rhi::ShaderModuleDesc fsDesc;
    fsDesc.spirvCode = reinterpret_cast<const u32*>(fragBlob->data.data());
    fsDesc.spirvSizeBytes = fragBlob->data.size();
    auto fsResult = device->createShaderModule(fsDesc);
    if (!fsResult) return tl::make_unexpected(fsResult.error());

    // Build material BindGroupLayout from "materialData" ParameterBlock reflection
    auto* materialBlock = findParameterBlock(unifiedShader.get(), "materialData");
    if (!materialBlock) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No 'materialData' ParameterBlock found"});
    }

    auto bglDesc = buildBindGroupLayoutFromReflection(*materialBlock, targetPass->bindingLayout);
    auto bglResult = device->createBindGroupLayout(bglDesc);
    if (!bglResult) return tl::make_unexpected(bglResult.error());

    // Get material CB size from reflection
    int16_t cbSize = findConstantBufferSize(*materialBlock);
    if (cbSize <= 0) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No constant buffer found in 'materialData'"});
    }
    u64 paramSize = static_cast<u64>(cbSize);

    // Create uniform buffer for material params
    rhi::BufferDesc bufDesc;
    bufDesc.size = paramSize;
    bufDesc.usage = rhi::BufferUsage::Uniform;
    auto bufResult = device->createBuffer(bufDesc);
    if (!bufResult) return tl::make_unexpected(bufResult.error());

    // Create default white texture
    auto texResult = TextureLoader::createWhiteTexture(device);
    if (!texResult) return tl::make_unexpected(texResult.error());

    // Assemble material
    auto mat = Ref<Material>::adopt(new Material());
    mat->type_ = type;
    mat->vertShader_ = std::move(*vsResult);
    mat->fragShader_ = std::move(*fsResult);
    mat->vertEntry_ = vertEP->name;
    mat->fragEntry_ = fragEP->name;
    mat->materialBindGroupLayout_ = std::move(*bglResult);
    mat->materialParamBufferSize_ = paramSize;
    mat->paramBuffer_ = std::move(*bufResult);
    mat->baseTexture_ = std::move(*texResult);

    // Build RenderPipeline
    auto buildResult = mat->buildPipeline(device, pipelineLayout, colorFormat, depthFormat);
    if (!buildResult) return tl::make_unexpected(buildResult.error());

    // Initial bind group update
    auto updateResult = mat->updateBindGroup(device);
    if (!updateResult) return tl::make_unexpected(updateResult.error());

    return mat;
}

Result<Ref<Material>> MaterialFactory::createUnlit(
    rhi::Device* device,
    rhi::PipelineLayout* pipelineLayout,
    rhi::TextureFormat colorFormat,
    rhi::TextureFormat depthFormat) {
    return MaterialFactory::createMaterialFromShaderData(
        device, pipelineLayout, colorFormat, depthFormat,
        s_unlitShaderData, sizeof(s_unlitShaderData),
        MaterialType::Unlit);
}

Result<Ref<Material>> MaterialFactory::createBasicLit(
    rhi::Device* device,
    rhi::PipelineLayout* pipelineLayout,
    rhi::TextureFormat colorFormat,
    rhi::TextureFormat depthFormat) {
    return MaterialFactory::createMaterialFromShaderData(
        device, pipelineLayout, colorFormat, depthFormat,
        s_basicLitShaderData, sizeof(s_basicLitShaderData),
        MaterialType::BasicLit);
}

Result<Ref<Material>> MaterialFactory::createUnlit(
    GraphicsContext* ctx,
    rhi::PipelineLayout* pipelineLayout) {
    return createUnlit(ctx->device(), pipelineLayout, ctx->colorFormat(), ctx->depthFormat());
}

Result<Ref<Material>> MaterialFactory::createBasicLit(
    GraphicsContext* ctx,
    rhi::PipelineLayout* pipelineLayout) {
    return createBasicLit(ctx->device(), pipelineLayout, ctx->colorFormat(), ctx->depthFormat());
}

} // namespace ln
