#include <LuminoCore/graphics/GraphicsModule.hpp>
#include <LuminoCore/graphics/TextureLoader.hpp>
#include <LuminoShader/UnifiedShader2.hpp>
#include <LuminoShader/UnifiedShaderSerializer2.hpp>

// Precompiled shader data (generated by luminosc during build).
static const unsigned char s_unlitShaderData[] = {
#include "shaders/Unlit.lcsh.inl"
};

static const unsigned char s_basicLitShaderData[] = {
#include "shaders/BasicLit.lcsh.inl"
};

static const unsigned char s_stencilMaskShaderData[] = {
#include "shaders/StencilMask.lcsh.inl"
};

namespace ln {

// ------ Helpers (moved from Material.cpp) ------------------------------------

static rhi::BindingType mapElementKind(shader::ParameterBlockElementKind kind) {
    switch (kind) {
    case shader::ParameterBlockElementKind_ConstantBuffer: return rhi::BindingType::UniformBuffer;
    case shader::ParameterBlockElementKind_Texture:        return rhi::BindingType::SampledTexture;
    case shader::ParameterBlockElementKind_SamplerState:   return rhi::BindingType::Sampler;
    case shader::ParameterBlockElementKind_StorageBuffer:  return rhi::BindingType::StorageBuffer;
    default: return rhi::BindingType::UniformBuffer;
    }
}

static rhi::BindGroupLayoutDesc buildBindGroupLayoutFromReflection(
    const shader::ParameterBlockLayout2& block,
    const shader::TargetBindingLayout2& mergedBindings) {
    rhi::BindGroupLayoutDesc desc;
    for (const auto& binding : mergedBindings.bindings) {
        if (binding.setIndex != block.setIndex) continue;
        rhi::BindGroupLayoutEntry entry;
        entry.binding = binding.bindingIndex;
        entry.type = mapElementKind(binding.kind);
        entry.visibility = static_cast<rhi::ShaderStage>(binding.used);
        desc.entries.push_back(entry);
    }
    return desc;
}

static const shader::ParameterBlockLayout2* findParameterBlock(
    const shader::UnifiedShader2* shader, const std::string& name) {
    for (const auto& block : shader->parameterBlocks()) {
        if (block.name == name) return &block;
    }
    return nullptr;
}

static int16_t findConstantBufferSize(const shader::ParameterBlockLayout2& block) {
    for (const auto& elem : block.elements) {
        if (elem.kind == shader::ParameterBlockElementKind_ConstantBuffer)
            return elem.constantBufferSize;
    }
    return -1;
}

// ------ GraphicsModule -------------------------------------------------------

Result<Ref<GraphicsModule>> GraphicsModule::create(const Settings& settings) {
    auto module = Ref<GraphicsModule>::adopt(new GraphicsModule());
    auto result = module->init(settings);
    if (!result) {
        return tl::make_unexpected(result.error());
    }
    return module;
}

GraphicsModule::GraphicsModule() {
}

GraphicsModule::~GraphicsModule() {
}

VoidResult GraphicsModule::init(const Settings& settings) {
    // Create the RHI device
    rhi::DeviceDesc devDesc;
    devDesc.backend = settings.preferredBackend;
    devDesc.enableValidation = settings.enableValidation;
    auto deviceResult = rhi::Device::create(devDesc);
    if (!deviceResult) return tl::make_unexpected(deviceResult.error());
    m_device = std::move(*deviceResult);

    // Initialize builtin shaders
    auto r1 = initBuiltinShader(BuiltinShader::Unlit, s_unlitShaderData, sizeof(s_unlitShaderData));
    if (!r1) return r1;
    auto r2 = initBuiltinShader(BuiltinShader::BasicLit, s_basicLitShaderData, sizeof(s_basicLitShaderData));
    if (!r2) return r2;
    auto r3 = initBuiltinShader(BuiltinShader::StencilMask, s_stencilMaskShaderData, sizeof(s_stencilMaskShaderData));
    if (!r3) return r3;

    // Create shared default white texture
    auto texResult = TextureLoader::createWhiteTexture(m_device.get());
    if (!texResult) return tl::make_unexpected(texResult.error());
    m_whiteTexture = std::move(*texResult);

    return LN_MAKE_SUCCESS();
}

VoidResult GraphicsModule::initBuiltinShader(BuiltinShader id, const unsigned char* data, size_t size) {
    // Deserialize the unified shader from the binary blob.
    auto loadResult = shader::UnifiedShaderSerializer2::loadFromData(data, size);
    if (!loadResult) return tl::make_unexpected(loadResult.error());
    auto unifiedShader = std::move(*loadResult);

    // Find the Forward pass for SPIR-V target.
    auto& globalPasses = unifiedShader->globalShaderPasses();
    if (globalPasses.empty()) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No shader passes found"});
    }

    auto* globalPass = globalPasses[0].get();
    auto targetPassId = globalPass->getTargetShaderPassId(shader::ShaderTarget_SPIRV);
    auto* targetPass = unifiedShader->targetShaderPass(targetPassId);
    if (!targetPass) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No SPIRV target pass"});
    }

    auto* vertEP = unifiedShader->targetEntryPoint(targetPass->vertEntryPointId);
    auto* fragEP = unifiedShader->targetEntryPoint(targetPass->fragEntryPointId);
    if (!vertEP || !fragEP) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "Missing entry points"});
    }

    auto* vertBlob = unifiedShader->blob(vertEP->codeBlobId);
    auto* fragBlob = unifiedShader->blob(fragEP->codeBlobId);

    // Create shader modules
    rhi::ShaderModuleDesc vsDesc;
    vsDesc.spirvCode = reinterpret_cast<const u32*>(vertBlob->data.data());
    vsDesc.spirvSizeBytes = vertBlob->data.size();
    auto vsResult = m_device->createShaderModule(vsDesc);
    if (!vsResult) return tl::make_unexpected(vsResult.error());

    rhi::ShaderModuleDesc fsDesc;
    fsDesc.spirvCode = reinterpret_cast<const u32*>(fragBlob->data.data());
    fsDesc.spirvSizeBytes = fragBlob->data.size();
    auto fsResult = m_device->createShaderModule(fsDesc);
    if (!fsResult) return tl::make_unexpected(fsResult.error());

    // Build material BindGroupLayout from "materialData" ParameterBlock reflection
    auto* materialBlock = findParameterBlock(unifiedShader.get(), "materialData");
    if (!materialBlock) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No 'materialData' ParameterBlock found"});
    }

    auto bglDesc = buildBindGroupLayoutFromReflection(*materialBlock, targetPass->bindingLayout);
    auto bglResult = m_device->createBindGroupLayout(bglDesc);
    if (!bglResult) return tl::make_unexpected(bglResult.error());

    // Get material CB size from reflection
    int16_t cbSize = findConstantBufferSize(*materialBlock);
    if (cbSize <= 0) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No constant buffer found in 'materialData'"});
    }

    // Store in cache
    auto& entry = m_builtinShaders[static_cast<int>(id)];
    entry.vertShader = std::move(*vsResult);
    entry.fragShader = std::move(*fsResult);
    entry.vertEntry = vertEP->name;
    entry.fragEntry = fragEP->name;
    entry.materialBindGroupLayout = std::move(*bglResult);
    entry.materialParamBufferSize = static_cast<u64>(cbSize);
    entry.initialized = true;

    return LN_MAKE_SUCCESS();
}

void GraphicsModule::dispose() {
    m_builtinShaders = {};
    m_whiteTexture.reset();
    m_device.reset();
}

} // namespace ln
