#include <LuminoCore/Graphics/GraphicsModule.hpp>
#include <LuminoCore/Graphics/ShaderPass.hpp>
#include <LuminoCore/Graphics/TextureLoader.hpp>
#include <LuminoShader/UnifiedShader2.hpp>
#include <LuminoShader/UnifiedShaderSerializer2.hpp>
#include "ShaderUtils.hpp"

// Precompiled shader data (generated by luminosc during build).
static const unsigned char s_unlitShaderData[] = {
#include "shaders/Unlit.lcsh.inl"
};

static const unsigned char s_basicLitShaderData[] = {
#include "shaders/BasicLit.lcsh.inl"
};

static const unsigned char s_stencilMaskShaderData[] = {
#include "shaders/StencilMask.lcsh.inl"
};

namespace ln {

using detail::buildBindGroupLayoutFromReflection;
using detail::findParameterBlock;
using detail::findConstantBufferSize;

//------------------------------------------------------------------------------
Result<Ref<GraphicsModule>> GraphicsModule::create(const Settings& settings) {
    auto module = Ref<GraphicsModule>::adopt(new GraphicsModule());
    auto result = module->init(settings);
    if (!result) {
        return tl::make_unexpected(result.error());
    }
    return module;
}

GraphicsModule::GraphicsModule() {
}

GraphicsModule::~GraphicsModule() {
}

VoidResult GraphicsModule::init(const Settings& settings) {
    // Create the RHI device
    rhi::DeviceDesc devDesc;
    devDesc.backend = settings.preferredBackend;
    devDesc.enableValidation = settings.enableValidation;
    auto deviceResult = rhi::Device::create(devDesc);
    if (!deviceResult) return tl::make_unexpected(deviceResult.error());
    m_device = std::move(*deviceResult);

    // Extract shared BindGroupLayoutDescs from BasicLit shader reflection
    auto r0 = extractSharedLayoutDescs(s_basicLitShaderData, sizeof(s_basicLitShaderData));
    if (!r0) return r0;

    // Initialize builtin shaders (now using ShaderPass)
    auto r1 = initBuiltinShader(BuiltinShader::Unlit, s_unlitShaderData, sizeof(s_unlitShaderData));
    if (!r1) return r1;
    auto r2 = initBuiltinShader(BuiltinShader::BasicLit, s_basicLitShaderData, sizeof(s_basicLitShaderData));
    if (!r2) return r2;
    auto r3 = initBuiltinShader(BuiltinShader::StencilMask, s_stencilMaskShaderData, sizeof(s_stencilMaskShaderData));
    if (!r3) return r3;

    // Create shared default white texture
    auto texResult = TextureLoader::createWhiteTexture(m_device.get());
    if (!texResult) return tl::make_unexpected(texResult.error());
    m_whiteTexture = std::move(*texResult);

    return LN_MAKE_SUCCESS();
}

VoidResult GraphicsModule::extractSharedLayoutDescs(const unsigned char* data, size_t size) {
    // Load BasicLit shader to extract BindGroupLayout info via reflection.
    auto loadResult = shader::UnifiedShaderSerializer2::loadFromData(data, size);
    if (!loadResult) return tl::make_unexpected(loadResult.error());
    auto unifiedShader = std::move(*loadResult);

    auto& globalPasses = unifiedShader->globalShaderPasses();
    if (globalPasses.empty()) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No shader passes found"});
    }
    auto targetPassId = globalPasses[0]->getTargetShaderPassId(shader::ShaderTarget_SPIRV);
    auto* targetPass = unifiedShader->targetShaderPass(targetPassId);
    if (!targetPass) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No SPIRV target pass"});
    }

    auto* viewBlock = findParameterBlock(unifiedShader.get(), "viewData");
    auto* sceneBlock = findParameterBlock(unifiedShader.get(), "sceneData");
    auto* objectBlock = findParameterBlock(unifiedShader.get(), "objectData");
    if (!viewBlock || !sceneBlock || !objectBlock) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError,
            "Missing required ParameterBlocks (viewData, sceneData, objectData)"});
    }

    // Build BindGroupLayoutDescs and set hasDynamicOffset for UBO entries
    m_viewLayoutDesc = buildBindGroupLayoutFromReflection(*viewBlock, targetPass->bindingLayout);
    for (auto& entry : m_viewLayoutDesc.entries) {
        if (entry.type == rhi::BindingType::UniformBuffer) entry.hasDynamicOffset = true;
    }

    m_sceneLayoutDesc = buildBindGroupLayoutFromReflection(*sceneBlock, targetPass->bindingLayout);
    for (auto& entry : m_sceneLayoutDesc.entries) {
        if (entry.type == rhi::BindingType::UniformBuffer) entry.hasDynamicOffset = true;
    }

    m_objectLayoutDesc = buildBindGroupLayoutFromReflection(*objectBlock, targetPass->bindingLayout);
    for (auto& entry : m_objectLayoutDesc.entries) {
        if (entry.type == rhi::BindingType::UniformBuffer) entry.hasDynamicOffset = true;
    }

    int16_t objectCBSize = findConstantBufferSize(*objectBlock);
    if (objectCBSize <= 0) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError,
            "Invalid object constant buffer size in reflection"});
    }
    m_objectUBOSize = static_cast<u64>(objectCBSize);

    return LN_MAKE_SUCCESS();
}

VoidResult GraphicsModule::initBuiltinShader(BuiltinShader id, const unsigned char* data, size_t size) {
    auto result = ShaderPass::createFromCompiledShader(
        data, size,
        m_viewLayoutDesc, m_sceneLayoutDesc, m_objectLayoutDesc,
        m_device.get());
    if (!result) return tl::make_unexpected(result.error());

    m_builtinShaders[static_cast<int>(id)] = std::move(*result);
    return LN_MAKE_SUCCESS();
}

void GraphicsModule::dispose() {
    m_builtinShaders = {};
    m_whiteTexture.reset();
    m_device.reset();
}

} // namespace ln
