#include <LuminoCore/Graphics/GraphicsModule.hpp>
#include <LuminoCore/Graphics/ShaderPass.hpp>
#include <LuminoCore/Graphics/TextureLoader.hpp>
#include <LuminoShader/UnifiedShader2.hpp>
#include <LuminoShader/UnifiedShaderSerializer2.hpp>

// Precompiled shader data (generated by luminosc during build).
static const unsigned char s_unlitShaderData[] = {
#include "../../shaders/Unlit.lcsh.inl"
};

static const unsigned char s_basicLitShaderData[] = {
#include "../../shaders/BasicLit.lcsh.inl"
};

static const unsigned char s_stencilMaskShaderData[] = {
#include "../../shaders/StencilMask.lcsh.inl"
};

namespace ln {

//------------------------------------------------------------------------------
Result<Ref<GraphicsModule>> GraphicsModule::create(const Settings& settings) {
    auto module = Ref<GraphicsModule>::adopt(new GraphicsModule());
    auto result = module->init(settings);
    if (!result) {
        return LN_FORWARD_ERROR(result);
    }
    return module;
}

GraphicsModule::GraphicsModule() {
}

GraphicsModule::~GraphicsModule() {
}

VoidResult GraphicsModule::init(const Settings& settings) {
    // Create the RHI device
    rhi::DeviceDesc devDesc;
    devDesc.backend = settings.preferredBackend;
    devDesc.enableValidation = settings.enableValidation;
    auto deviceResult = rhi::Device::create(devDesc);
    if (!deviceResult) return LN_FORWARD_ERROR(deviceResult);
    m_device = std::move(*deviceResult);

    // Initialize builtin shaders (now using ShaderPass)
    auto r1 = initBuiltinShader(BuiltinShader::Unlit, s_unlitShaderData, sizeof(s_unlitShaderData));
    if (!r1) return r1;
    auto r2 = initBuiltinShader(BuiltinShader::BasicLit, s_basicLitShaderData, sizeof(s_basicLitShaderData));
    if (!r2) return r2;
    auto r3 = initBuiltinShader(BuiltinShader::StencilMask, s_stencilMaskShaderData, sizeof(s_stencilMaskShaderData));
    if (!r3) return r3;

    // Create shared default white texture
    auto texResult = TextureLoader::createWhiteTexture(m_device.get());
    if (!texResult) return LN_FORWARD_ERROR(texResult);
    m_whiteTexture = std::move(*texResult);

    return LN_MAKE_SUCCESS();
}

VoidResult GraphicsModule::initBuiltinShader(BuiltinShader id, const unsigned char* data, size_t size) {
    // Deserialize once to discover how many passes the shader exposes.
    auto loadResult = shader::UnifiedShaderSerializer2::loadFromData(data, size);
    if (!loadResult) {
        return LN_FORWARD_ERROR(loadResult);
    }
    auto unifiedShader = std::move(*loadResult);

    auto& globalPasses = unifiedShader->globalShaderPasses();
    if (globalPasses.empty()) {
        return LN_MAKE_ERROR("Builtin shader contains no passes");
    }

    auto& slot = m_builtinShaders[static_cast<int>(id)];
    slot.clear();
    slot.reserve(globalPasses.size());
    for (size_t i = 0; i < globalPasses.size(); ++i) {
        auto result = ShaderPass::createFromCompiledShader(
            data, size, m_device.get(), i);
        if (!result) {
            return LN_FORWARD_ERROR(result);
        }
        slot.push_back(std::move(*result));
    }
    return LN_MAKE_SUCCESS();
}

void GraphicsModule::dispose() {
    for (auto& passes : m_builtinShaders) {
        passes.clear();
    }
    m_whiteTexture.reset();
    m_device.reset();
}

} // namespace ln
