#include <LuminoCore/graphics/Material.hpp>
#include <LuminoCore/graphics/GraphicsContext.hpp>
#include <LuminoCore/graphics/TextureLoader.hpp>
#include <LuminoShader/UnifiedShader2.hpp>
#include <LuminoShader/UnifiedShaderSerializer2.hpp>
#include <cstring>

// Precompiled shader data (generated by luminosc during build).
// These are hex-array .inl files included as static byte arrays.
static const unsigned char s_unlitShaderData[] = {
#include "shaders/Unlit.lcsh.inl"
};

static const unsigned char s_basicLitShaderData[] = {
#include "shaders/BasicLit.lcsh.inl"
};

namespace ln {

// ------ Helpers --------------------------------------------------------------------------------------------------------------------------

static rhi::BindingType mapElementKind(shader::ParameterBlockElementKind kind) {
    switch (kind) {
    case shader::ParameterBlockElementKind_ConstantBuffer: return rhi::BindingType::UniformBuffer;
    case shader::ParameterBlockElementKind_Texture:        return rhi::BindingType::SampledTexture;
    case shader::ParameterBlockElementKind_SamplerState:   return rhi::BindingType::Sampler;
    case shader::ParameterBlockElementKind_StorageBuffer:  return rhi::BindingType::StorageBuffer;
    default: return rhi::BindingType::UniformBuffer;
    }
}

static rhi::BindGroupLayoutDesc buildBindGroupLayoutFromReflection(
    const shader::ParameterBlockLayout2& block,
    const shader::TargetBindingLayout2& mergedBindings) {
    rhi::BindGroupLayoutDesc desc;
    for (const auto& binding : mergedBindings.bindings) {
        if (binding.setIndex != block.setIndex) continue;
        rhi::BindGroupLayoutEntry entry;
        entry.binding = binding.bindingIndex;
        entry.type = mapElementKind(binding.kind);
        entry.visibility = static_cast<rhi::ShaderStage>(binding.used);
        desc.entries.push_back(entry);
    }
    return desc;
}

static const shader::ParameterBlockLayout2* findParameterBlock(
    const shader::UnifiedShader2* shader, const std::string& name) {
    for (const auto& block : shader->parameterBlocks()) {
        if (block.name == name) return &block;
    }
    return nullptr;
}

static int16_t findConstantBufferSize(const shader::ParameterBlockLayout2& block) {
    if (block.hasImplicitConstantBuffer) {
        for (const auto& elem : block.elements) {
            if (elem.kind == shader::ParameterBlockElementKind_ConstantBuffer)
                return elem.constantBufferSize;
        }
    } else {
        for (const auto& elem : block.elements) {
            if (elem.kind == shader::ParameterBlockElementKind_ConstantBuffer)
                return elem.constantBufferSize;
        }
    }
    return -1;
}

// ------ Material ------------------------------------------------------------------------------------------------------------------------

void Material::setColor(const Color& color) {
    m_baseColor = color;
    markDirty();
}

void Material::setTexture(rhi::Texture* texture) {
    if (texture) {
        texture->addRef();
        m_baseTexture = Ref<rhi::Texture>::adopt(texture);
    } else {
        m_baseTexture.reset();
    }
    markDirty();
}

void Material::setSpecular(const Color& color, f32 shininess) {
    m_specularColor = color;
    m_shininess = shininess;
    markDirty();
}

void Material::writeMaterialUBO(void* dst) const {
    if (m_type == MaterialType::Unlit) {
        UnlitMaterialParamsUBO ubo;
        ubo.color[0] = m_baseColor.r; ubo.color[1] = m_baseColor.g;
        ubo.color[2] = m_baseColor.b; ubo.color[3] = m_baseColor.a;
        std::memcpy(dst, &ubo, sizeof(ubo));
    } else {
        BasicLitMaterialParamsUBO ubo;
        ubo.color[0] = m_baseColor.r; ubo.color[1] = m_baseColor.g;
        ubo.color[2] = m_baseColor.b; ubo.color[3] = m_baseColor.a;
        ubo.specular[0] = m_specularColor.r; ubo.specular[1] = m_specularColor.g;
        ubo.specular[2] = m_specularColor.b; ubo.specular[3] = m_shininess;
        std::memcpy(dst, &ubo, sizeof(ubo));
    }
}

void Material::setBlendEnabled(bool enabled) { m_blendEnabled = enabled; }
void Material::setCullMode(rhi::CullMode mode) { m_cullMode = mode; }
void Material::setDepthTestEnabled(bool enabled) { m_depthTestEnabled = enabled; }
void Material::setDepthWriteEnabled(bool enabled) { m_depthWriteEnabled = enabled; }

// ------ Helper: load shaders from precompiled .lcsh data ----------------------------------------

Result<Ref<Material>> MaterialFactory::createMaterialFromShaderData(
    rhi::Device* device,
    const unsigned char* shaderData, size_t shaderDataSize,
    MaterialType type) {

    // Deserialize the unified shader from the binary blob.
    auto loadResult = shader::UnifiedShaderSerializer2::loadFromData(shaderData, shaderDataSize);
    if (!loadResult) return tl::make_unexpected(loadResult.error());
    auto unifiedShader = std::move(*loadResult);

    // Find the Forward pass for SPIR-V target.
    auto& globalPasses = unifiedShader->globalShaderPasses();
    if (globalPasses.empty()) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No shader passes found"});
    }

    auto* globalPass = globalPasses[0].get();
    auto targetPassId = globalPass->getTargetShaderPassId(shader::ShaderTarget_SPIRV);
    auto* targetPass = unifiedShader->targetShaderPass(targetPassId);
    if (!targetPass) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No SPIRV target pass"});
    }

    auto* vertEP = unifiedShader->targetEntryPoint(targetPass->vertEntryPointId);
    auto* fragEP = unifiedShader->targetEntryPoint(targetPass->fragEntryPointId);
    if (!vertEP || !fragEP) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "Missing entry points"});
    }

    auto* vertBlob = unifiedShader->blob(vertEP->codeBlobId);
    auto* fragBlob = unifiedShader->blob(fragEP->codeBlobId);

    // Create shader modules
    rhi::ShaderModuleDesc vsDesc;
    vsDesc.spirvCode = reinterpret_cast<const u32*>(vertBlob->data.data());
    vsDesc.spirvSizeBytes = vertBlob->data.size();
    auto vsResult = device->createShaderModule(vsDesc);
    if (!vsResult) return tl::make_unexpected(vsResult.error());

    rhi::ShaderModuleDesc fsDesc;
    fsDesc.spirvCode = reinterpret_cast<const u32*>(fragBlob->data.data());
    fsDesc.spirvSizeBytes = fragBlob->data.size();
    auto fsResult = device->createShaderModule(fsDesc);
    if (!fsResult) return tl::make_unexpected(fsResult.error());

    // Build material BindGroupLayout from "materialData" ParameterBlock reflection
    auto* materialBlock = findParameterBlock(unifiedShader.get(), "materialData");
    if (!materialBlock) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No 'materialData' ParameterBlock found"});
    }

    auto bglDesc = buildBindGroupLayoutFromReflection(*materialBlock, targetPass->bindingLayout);
    auto bglResult = device->createBindGroupLayout(bglDesc);
    if (!bglResult) return tl::make_unexpected(bglResult.error());

    // Get material CB size from reflection
    int16_t cbSize = findConstantBufferSize(*materialBlock);
    if (cbSize <= 0) {
        return tl::make_unexpected(Error{ErrorCode::RuntimeError, "No constant buffer found in 'materialData'"});
    }
    u64 paramSize = static_cast<u64>(cbSize);

    // Create default white texture
    auto texResult = TextureLoader::createWhiteTexture(device);
    if (!texResult) return tl::make_unexpected(texResult.error());

    // Assemble material
    auto mat = Ref<Material>::adopt(new Material());
    mat->m_type = type;
    mat->m_vertShader = std::move(*vsResult);
    mat->m_fragShader = std::move(*fsResult);
    mat->m_vertEntry = vertEP->name;
    mat->m_fragEntry = fragEP->name;
    mat->m_materialBindGroupLayout = std::move(*bglResult);
    mat->m_materialParamBufferSize = paramSize;
    mat->m_baseTexture = std::move(*texResult);

    return mat;
}

Result<Ref<Material>> MaterialFactory::createUnlit(rhi::Device* device) {
    return MaterialFactory::createMaterialFromShaderData(
        device,
        s_unlitShaderData, sizeof(s_unlitShaderData),
        MaterialType::Unlit);
}

Result<Ref<Material>> MaterialFactory::createBasicLit(rhi::Device* device) {
    return MaterialFactory::createMaterialFromShaderData(
        device,
        s_basicLitShaderData, sizeof(s_basicLitShaderData),
        MaterialType::BasicLit);
}

Result<Ref<Material>> MaterialFactory::createUnlit(GraphicsContext* ctx) {
    return createUnlit(ctx->device());
}

Result<Ref<Material>> MaterialFactory::createBasicLit(GraphicsContext* ctx) {
    return createBasicLit(ctx->device());
}

} // namespace ln
