
#ifndef __lumino__
#define __lumino__

#ifdef LUMINO_DEBUG
    #regcmd "_hsp3cmdinit@4","LuminoHSPd.dll", 6
#else
    #regcmd "_hsp3cmdinit@4","LuminoHSP.dll", 6
#endif

#const global LN_TRUE 1
#const global LN_FALSE 0
#const global LN_NULL_HANDLE 0

#const global LN_MOUSE_BUTTONS_NONE 0
#const global LN_MOUSE_BUTTONS_LEFT 1
#const global LN_MOUSE_BUTTONS_RIGHT 2
#const global LN_MOUSE_BUTTONS_MIDDLE 3
#const global LN_MOUSE_BUTTONS_X1 4
#const global LN_MOUSE_BUTTONS_X2 5
#const global LN_PIXEL_FORMAT_UNKNOWN 0
#const global LN_PIXEL_FORMAT_A8 1
#const global LN_PIXEL_FORMAT_RGBA8 2
#const global LN_PIXEL_FORMAT_RGB8 3
#const global LN_PIXEL_FORMAT_RGBA32F 4
#const global LN_PIXEL_FORMAT_R32S 5
#const global LN_TEXTURE_FORMAT_UNKNOWN 0
#const global LN_TEXTURE_FORMAT_RGBA8 1
#const global LN_TEXTURE_FORMAT_RGB8 2
#const global LN_TEXTURE_FORMAT_RGBA16F 3
#const global LN_TEXTURE_FORMAT_RGBA32F 4
#const global LN_TEXTURE_FORMAT_R16F 5
#const global LN_TEXTURE_FORMAT_R32F 6
#const global LN_TEXTURE_FORMAT_R32S 7
#const global LN_DEPTH_BUFFER_FORMAT_D24S8 0
#const global LN_SCENE_CLEAR_MODE_NONE 0
#const global LN_SCENE_CLEAR_MODE_COLOR_AND_DEPTH 1
#const global LN_SCENE_CLEAR_MODE_SKY 2
#const global LN_SCENE_CLEAR_MODE_SKY0 3
#const global LN_SCENE_CLEAR_MODE_SKY_DOME 4
#const global LN_HIERARCHICAL_ANIMATION_MODE_ALLOW_TRANSLATION_ONLY_ROOT 0
#const global LN_HIERARCHICAL_ANIMATION_MODE_ALLOW_TRANSLATION_ONLY_ROOT_Y 1
#const global LN_HIERARCHICAL_ANIMATION_MODE_ALLOW_TRANSLATION 2
#const global LN_HIERARCHICAL_ANIMATION_MODE_DISABLE_TRANSLATION 3
#const global LN_LEVEL_TRANSITION_EFFECT_MODE_NONE 0
#const global LN_LEVEL_TRANSITION_EFFECT_MODE_FADE_IN_OUT 1
#const global LN_LEVEL_TRANSITION_EFFECT_MODE_CROSS_FADE 2
#const global LN_UILAYOUT_ORIENTATION_HORIZONTAL 0
#const global LN_UILAYOUT_ORIENTATION_VERTICAL 1
#const global LN_UILAYOUT_ORIENTATION_REVERSE_HORIZONTAL 2
#const global LN_UILAYOUT_ORIENTATION_REVERSE_VERTICAL 3
#const global LN_UIVALIGNMENT_TOP 0
#const global LN_UIVALIGNMENT_CENTER 1
#const global LN_UIVALIGNMENT_BOTTOM 2
#const global LN_UIVALIGNMENT_STRETCH 3
#const global LN_UIHALIGNMENT_LEFT 0
#const global LN_UIHALIGNMENT_CENTER 1
#const global LN_UIHALIGNMENT_RIGHT 2
#const global LN_UIHALIGNMENT_STRETCH 3
#const global LN_UILIST_SUBMIT_MODE_SINGLE 0
#const global LN_UILIST_SUBMIT_MODE_DOUBLE 1

#cmd LNVector3 $2B
#cmd LNVector3_GetX $3B3
#cmd LNVector3_SetX $3B5
#cmd LNVector3_GetY $3B6
#cmd LNVector3_SetY $3B8
#cmd LNVector3_GetZ $3B9
#cmd LNVector3_SetZ $3BB
#cmd LNVector3_SetZeros $2F
#cmd LNVector3_Set $30
#cmd LNVector3_Get $34
#cmd LNVector3_Length $38
#cmd LNVector3_LengthSquared $39
#cmd LNVector3_MutatingNormalize $3A
#cmd LNVector3_NormalizeXYZ $3B
#cmd LNVector3_Normalize $3F
#cmd LNVector4 $41
#cmd LNVector4_GetX $3D2
#cmd LNVector4_SetX $3D4
#cmd LNVector4_GetY $3D5
#cmd LNVector4_SetY $3D7
#cmd LNVector4_GetZ $3D8
#cmd LNVector4_SetZ $3DA
#cmd LNVector4_GetW $3DB
#cmd LNVector4_SetW $3DD
#cmd LNVector4_SetZeros $46
#cmd LNVector4_Set $47
#cmd LNQuaternion $4C
#cmd LNQuaternion_GetX $3F0
#cmd LNQuaternion_SetX $3F2
#cmd LNQuaternion_GetY $3F3
#cmd LNQuaternion_SetY $3F5
#cmd LNQuaternion_GetZ $3F6
#cmd LNQuaternion_SetZ $3F8
#cmd LNQuaternion_GetW $3F9
#cmd LNQuaternion_SetW $3FB
#cmd LNQuaternion_SetZeros $51
#cmd LNQuaternion_Set $52
#cmd LNQuaternion_SetFromAxis $57
#cmd LNMatrix $5A
#cmd LNMatrix_GetRow0 $40F
#cmd LNMatrix_SetRow0 $411
#cmd LNMatrix_GetRow1 $412
#cmd LNMatrix_SetRow1 $414
#cmd LNMatrix_GetRow2 $415
#cmd LNMatrix_SetRow2 $417
#cmd LNMatrix_GetRow3 $418
#cmd LNMatrix_SetRow3 $41A
#cmd LNMatrix_SetZeros $5F
#cmd LNMatrix_Set $60
#cmd LNColor $F9
#cmd LNColor_GetR $498
#cmd LNColor_SetR $49A
#cmd LNColor_GetG $49B
#cmd LNColor_SetG $49D
#cmd LNColor_GetB $49E
#cmd LNColor_SetB $4A0
#cmd LNColor_GetA $4A1
#cmd LNColor_SetA $4A3
#cmd LNColor_SetZeros $FE
#cmd LNColor_Set $FF
#cmd LNPoint $104
#cmd LNPoint_GetX $4B7
#cmd LNPoint_SetX $4B9
#cmd LNPoint_GetY $4BA
#cmd LNPoint_SetY $4BC
#cmd LNPoint_SetZeros $107
#cmd LNPoint_Set $108
#cmd LNSize $10B
#cmd LNSize_GetWidth $4C7
#cmd LNSize_SetWidth $4C9
#cmd LNSize_GetHeight $4CA
#cmd LNSize_SetHeight $4CC
#cmd LNSize_SetZeros $10E
#cmd LNSize_Set $10F
#cmd LNRect $112
#cmd LNRect_GetX $4D7
#cmd LNRect_SetX $4D9
#cmd LNRect_GetY $4DA
#cmd LNRect_SetY $4DC
#cmd LNRect_GetWidth $4DD
#cmd LNRect_SetWidth $4DF
#cmd LNRect_GetHeight $4E0
#cmd LNRect_SetHeight $4E2
#cmd LNRect_SetZeros $117
#cmd LNRect_Set $118
#cmd LNRect_GetLeft $11D
#cmd LNRect_SetSize $11E
#cmd LNRect_GetSize $120
#cmd LNThickness $121
#cmd LNThickness_GetLeft $4FB
#cmd LNThickness_SetLeft $4FD
#cmd LNThickness_GetTop $4FE
#cmd LNThickness_SetTop $500
#cmd LNThickness_GetRight $501
#cmd LNThickness_SetRight $503
#cmd LNThickness_GetBottom $504
#cmd LNThickness_SetBottom $506
#cmd LNThickness_SetZeros $126
#cmd LNThickness_Set $127

#cmd LNObject_Release $74
#cmd LNObject_Retain $75
#cmd LNObject_GetReferenceCount $76
#cmd LNObject_SetPrototype_OnSerialize $6EF
#cmd LNEventConnection_SetPrototype_OnSerialize $6FA
#cmd LNPromiseFailureDelegate_Create $435
#cmd LNVariant_Create $7B
#cmd LNVariant_SetInt $7C
#cmd LNVariant_GetInt $7E
#cmd LNVariant_SetPrototype_OnSerialize $705
#cmd LNZVTestDelegate1_Create $43E
#cmd LNZVTestDelegate2_Create $444
#cmd LNZVTestDelegate3_Create $449
#cmd LNZVTestEventHandler1_Create $44E
#cmd LNZVTestEventHandler2_Create $453
#cmd LNZVTestPromise1_ThenWith $456
#cmd LNZVTestPromise1_CatchWith $458
#cmd LNZVTestPromise2_ThenWith $45C
#cmd LNZVTestPromise2_CatchWith $45E
#cmd LNZVTestClass1_Create $A7
#cmd LNZVTestClass1_SetTestDelegate1 $91
#cmd LNZVTestClass1_SetTestDelegate2 $93
#cmd LNZVTestClass1_SetTestDelegate3 $95
#cmd LNZVTestClass1_CallTestDelegate1 $97
#cmd LNZVTestClass1_CallTestDelegate2 $99
#cmd LNZVTestClass1_CallTestDelegate3 $9C
#cmd LNZVTestClass1_LoadAsync $9D
#cmd LNZVTestClass1_ExecuteAsync $9F
#cmd LNZVTestClass1_GetFilePath $A0
#cmd LNZVTestClass1_ConnectOnEvent1 $A1
#cmd LNZVTestClass1_RaiseEvent1 $A3
#cmd LNZVTestClass1_ConnectOnEvent2 $A4
#cmd LNZVTestClass1_RaiseEvent2 $A6
#cmd LNZVTestClass1_SetPrototype_OnSerialize $710
#cmd LNZVTestEventArgs1_Create $AA
#cmd LNZVTestEventArgs1_CreateWithValue $AB
#cmd LNZVTestEventArgs1_GetValue $A9
#cmd LNZVTestEventArgs1_SetPrototype_OnSerialize $71B
#cmd LNSerializer2_SetPrototype_OnSerialize $726
#cmd LNAssetModel_Create $B7
#cmd LNAssetModel_Target $B6
#cmd LNAssetModel_SetPrototype_OnSerialize $731
#cmd LNAssets_SaveAssetToLocalFile $BA
#cmd LNAssets_LoadAssetFromLocalFile $BD
#cmd LNAssets_LoadAsset $BF
#cmd LNAssets_ReloadAsset $C1
#cmd LNAudio_PlayBGM $C5
#cmd LNAudio_StopBGM $CA
#cmd LNAudio_PlayBGS $CC
#cmd LNAudio_StopBGS $D1
#cmd LNAudio_PlayME $D3
#cmd LNAudio_StopME $D7
#cmd LNAudio_PlaySE $D8
#cmd LNAudio_PlaySE3D $DC
#cmd LNAudio_StopSE $E2
#cmd LNTexture2DDelegate_Create $490
#cmd LNTexture2DPromise_ThenWith $493
#cmd LNTexture2DPromise_CatchWith $495
#cmd LNTexture_SetPrototype_OnSerialize $73C
#cmd LNTexture2D_Create $132
#cmd LNTexture2D_CreateWithFormat $135
#cmd LNTexture2D_Load $12E
#cmd LNTexture2D_LoadEmoji $130
#cmd LNTexture2D_SetPrototype_OnSerialize $747
#cmd LNRenderView_SetPrototype_OnSerialize $752
#cmd LNSkinnedMeshModel_Load $141
#cmd LNSkinnedMeshModel_GetAnimationController $143
#cmd LNSkinnedMeshModel_SetPrototype_OnSerialize $75D
#cmd LNAnimationController_AddClip $145
#cmd LNAnimationController_Play $147
#cmd LNAnimationController_SetPrototype_OnSerialize $768
#cmd LNCollisionShape_SetPrototype_OnSerialize $773
#cmd LNBoxCollisionShape_Create $14C
#cmd LNBoxCollisionShape_CreateWHD $14E
#cmd LNBoxCollisionShape_SetPrototype_OnSerialize $77E
#cmd LNAnimationClip_Load $158
#cmd LNAnimationClip_SetHierarchicalAnimationMode $15A
#cmd LNAnimationClip_HierarchicalAnimationMode $15C
#cmd LNAnimationClip_SetPrototype_OnSerialize $789
#cmd LNAnimationState_SetPrototype_OnSerialize $794
#cmd LNComponent_SetPrototype_OnSerialize $79F
#cmd LNVisualComponent_SetVisible $160
#cmd LNVisualComponent_IsVisible $162
#cmd LNVisualComponent_SetPrototype_OnSerialize $7AA
#cmd LNSpriteComponent_SetTexture $164
#cmd LNSpriteComponent_SetPrototype_OnSerialize $7B5
#cmd LNCollisionEventHandler_Create $534
#cmd LNCharacterController_Create $181
#cmd LNCharacterController_SetVelocity $16E
#cmd LNCharacterController_GetVelocity $170
#cmd LNCharacterController_SetInputControlEnabled $171
#cmd LNCharacterController_SetCameraControlEnabled $173
#cmd LNCharacterController_SetHeight $175
#cmd LNCharacterController_GetHeight $177
#cmd LNCharacterController_SetCameraRadius $178
#cmd LNCharacterController_GetCameraRadius $17A
#cmd LNCharacterController_SetCollisionEnter $17B
#cmd LNCharacterController_SetCollisionLeave $17D
#cmd LNCharacterController_SetCollisionStay $17F
#cmd LNCharacterController_SetPrototype_OnSerialize $7C0
#cmd LNWorld_Add $183
#cmd LNWorld_SetPrototype_OnSerialize $7CB
#cmd LNComponentList_GetLength $54F
#cmd LNComponentList_GetItem $551
#cmd LNComponentList_SetPrototype_OnSerialize $7D6
#cmd LNWorldObject_Create $1B9
#cmd LNWorldObject_SetPosition $187
#cmd LNWorldObject_SetPositionXYZ $189
#cmd LNWorldObject_GetPosition $18D
#cmd LNWorldObject_SetRotationQuaternion $18E
#cmd LNWorldObject_SetRotation $190
#cmd LNWorldObject_GetRotation $194
#cmd LNWorldObject_SetScale $195
#cmd LNWorldObject_SetScaleS $197
#cmd LNWorldObject_SetScaleXYZ $199
#cmd LNWorldObject_GetScale $19D
#cmd LNWorldObject_SetCenterPoint $19E
#cmd LNWorldObject_SetCenterPointXYZ $1A0
#cmd LNWorldObject_GetCenterPoint $1A4
#cmd LNWorldObject_LookAt $1A5
#cmd LNWorldObject_LookAtXYZ $1A7
#cmd LNWorldObject_AddComponent $1AB
#cmd LNWorldObject_RemoveComponent $1AD
#cmd LNWorldObject_AddTag $1AF
#cmd LNWorldObject_RemoveTag $1B1
#cmd LNWorldObject_HasTag $1B3
#cmd LNWorldObject_Destroy $1B5
#cmd LNWorldObject_GetComponents $1B6
#cmd LNWorldObject_SetPrototype_OnSerialize $7E1
#cmd LNWorldObject_SetPrototype_OnUpdate $7EC
#cmd LNVisualObject_SetVisible $1BB
#cmd LNVisualObject_IsVisible $1BD
#cmd LNVisualObject_SetPrototype_OnSerialize $7F7
#cmd LNVisualObject_SetPrototype_OnUpdate $802
#cmd LNCamera_SetPrototype_OnSerialize $80D
#cmd LNCamera_SetPrototype_OnUpdate $818
#cmd LNEnvironmentLight_SetEnabled $1C0
#cmd LNEnvironmentLight_IsEnabled $1C2
#cmd LNEnvironmentLight_SetColor $1C3
#cmd LNEnvironmentLight_GetColor $1C5
#cmd LNEnvironmentLight_SetAmbientColor $1C6
#cmd LNEnvironmentLight_GetAmbientColor $1C8
#cmd LNEnvironmentLight_GetSkyColor $1C9
#cmd LNEnvironmentLight_SetSkyColor $1CA
#cmd LNEnvironmentLight_GetGroundColor $1CC
#cmd LNEnvironmentLight_SetGroundColor $1CD
#cmd LNEnvironmentLight_SetIntensity $1CF
#cmd LNEnvironmentLight_GetIntensity $1D1
#cmd LNEnvironmentLight_SetShadowEffectiveDistance $1D2
#cmd LNEnvironmentLight_GetShadowEffectiveDistance $1D4
#cmd LNEnvironmentLight_SetShadowEffectiveDepth $1D5
#cmd LNEnvironmentLight_GetShadowEffectiveDepth $1D7
#cmd LNEnvironmentLight_SetPrototype_OnSerialize $823
#cmd LNEnvironmentLight_SetPrototype_OnUpdate $82E
#cmd LNDirectionalLight_Create $1E8
#cmd LNDirectionalLight_CreateWithColor $1E9
#cmd LNDirectionalLight_SetEnabled $1D9
#cmd LNDirectionalLight_IsEnabled $1DB
#cmd LNDirectionalLight_SetColor $1DC
#cmd LNDirectionalLight_GetColor $1DE
#cmd LNDirectionalLight_SetIntensity $1DF
#cmd LNDirectionalLight_GetIntensity $1E1
#cmd LNDirectionalLight_SetShadowEffectiveDistance $1E2
#cmd LNDirectionalLight_GetShadowEffectiveDistance $1E4
#cmd LNDirectionalLight_SetShadowEffectiveDepth $1E5
#cmd LNDirectionalLight_GetShadowEffectiveDepth $1E7
#cmd LNDirectionalLight_SetPrototype_OnSerialize $839
#cmd LNDirectionalLight_SetPrototype_OnUpdate $844
#cmd LNPointLight_Create $1FB
#cmd LNPointLight_CreateWithColorAndRange $1FC
#cmd LNPointLight_SetEnabled $1EC
#cmd LNPointLight_IsEnabled $1EE
#cmd LNPointLight_SetColor $1EF
#cmd LNPointLight_GetColor $1F1
#cmd LNPointLight_SetIntensity $1F2
#cmd LNPointLight_GetIntensity $1F4
#cmd LNPointLight_SetRange $1F5
#cmd LNPointLight_GetRange $1F7
#cmd LNPointLight_SetAttenuation $1F8
#cmd LNPointLight_GetAttenuation $1FA
#cmd LNPointLight_SetPrototype_OnSerialize $84F
#cmd LNPointLight_SetPrototype_OnUpdate $85A
#cmd LNSpotLight_Create $215
#cmd LNSpotLight_CreateWithColorAndRange $216
#cmd LNSpotLight_SetEnabled $200
#cmd LNSpotLight_IsEnabled $202
#cmd LNSpotLight_SetColor $203
#cmd LNSpotLight_GetColor $205
#cmd LNSpotLight_SetIntensity $206
#cmd LNSpotLight_GetIntensity $208
#cmd LNSpotLight_SetRange $209
#cmd LNSpotLight_GetRange $20B
#cmd LNSpotLight_SetAttenuation $20C
#cmd LNSpotLight_GetAttenuation $20E
#cmd LNSpotLight_SetAngle $20F
#cmd LNSpotLight_GetAngle $211
#cmd LNSpotLight_SetPenumbra $212
#cmd LNSpotLight_GetPenumbra $214
#cmd LNSpotLight_SetPrototype_OnSerialize $865
#cmd LNSpotLight_SetPrototype_OnUpdate $870
#cmd LNTestDelegate_Create $5F5
#cmd LNSprite_Create $22C
#cmd LNSprite_CreateWithTexture $22D
#cmd LNSprite_CreateWithTextureAndSize $22F
#cmd LNSprite_SetTexture $21E
#cmd LNSprite_SetSize $220
#cmd LNSprite_SetSizeWH $222
#cmd LNSprite_SetSourceRectXYWH $225
#cmd LNSprite_SetCallerTest $22A
#cmd LNSprite_SetPrototype_OnSerialize $87B
#cmd LNSprite_SetPrototype_OnUpdate $886
#cmd LNCameraOrbitControlComponent_Create $234
#cmd LNCameraOrbitControlComponent_SetPrototype_OnSerialize $891
#cmd LNRaycaster_FromScreen $236
#cmd LNRaycaster_IntersectPlane $238
#cmd LNRaycaster_SetPrototype_OnSerialize $89C
#cmd LNRaycastResult_GetPoint $23D
#cmd LNRaycastResult_SetPrototype_OnSerialize $8A7
#cmd LNWorldRenderView_SetGuideGridEnabled $23F
#cmd LNWorldRenderView_GetGuideGridEnabled $241
#cmd LNWorldRenderView_SetPrototype_OnSerialize $8B2
#cmd LNBoxMesh_Create $243
#cmd LNBoxMesh_SetPrototype_OnSerialize $8BD
#cmd LNBoxMesh_SetPrototype_OnUpdate $8C8
#cmd LNPlaneMesh_Create $245
#cmd LNPlaneMesh_SetPrototype_OnSerialize $8D3
#cmd LNPlaneMesh_SetPrototype_OnUpdate $8DE
#cmd LNStaticMesh_Load $247
#cmd LNStaticMesh_MakeCollisionBody $249
#cmd LNStaticMesh_SetPrototype_OnSerialize $8E9
#cmd LNStaticMesh_SetPrototype_OnUpdate $8F4
#cmd LNSkinnedMeshComponent_Create $24E
#cmd LNSkinnedMeshComponent_SetModel $24C
#cmd LNSkinnedMeshComponent_SetPrototype_OnSerialize $8FF
#cmd LNCollision_GetWorldObject $250
#cmd LNCollision_SetPrototype_OnSerialize $90A
#cmd LNTriggerBodyComponent_Create $254
#cmd LNTriggerBodyComponent_AddCollisionShape $252
#cmd LNTriggerBodyComponent_SetPrototype_OnSerialize $915
#cmd LNScene_SetClearMode $256
#cmd LNScene_SetSkyColor $258
#cmd LNScene_SetSkyHorizonColor $25A
#cmd LNScene_SetSkyCloudColor $25C
#cmd LNScene_SetSkyOverlayColor $25E
#cmd LNScene_GotoLevel $260
#cmd LNScene_CallLevel $263
#cmd LNScene_ReturnLevel $266
#cmd LNScene_ActiveLevel $268
#cmd LNScene_IsTransitionEffectRunning $269
#cmd LNScene_SetTransitionEffectMode $26A
#cmd LNScene_TransitionEffectMode $26C
#cmd LNScene_SetTransitionDuration $26D
#cmd LNScene_TransitionDuration $26F
#cmd LNScene_SetTransitionEffectColor $270
#cmd LNScene_TransitionEffectColor $272
#cmd LNScene_SetTransitionEffectMaskTexture $273
#cmd LNScene_TransitionEffectMaskTexture $275
#cmd LNScene_SetTransitionEffectVague $276
#cmd LNScene_TransitionEffectVague $278
#cmd LNScene_StartFadeOut $279
#cmd LNScene_StartFadeIn $27A
#cmd LNScene_SetScreenBlendColor $27B
#cmd LNScene_ScreenBlendColor $27D
#cmd LNLevel_Create $28D
#cmd LNLevel_AddObject $27F
#cmd LNLevel_RemoveObject $281
#cmd LNLevel_AddSubLevel $283
#cmd LNLevel_RemoveSubLevel $285
#cmd LNLevel_RemoveAllSubLevels $287
#cmd LNLevel_SetPrototype_OnSerialize $920
#cmd LNLevel_SetPrototype_OnStart $92B
#cmd LNLevel_SetPrototype_OnStop $936
#cmd LNLevel_SetPrototype_OnPause $941
#cmd LNLevel_SetPrototype_OnResume $94C
#cmd LNLevel_SetPrototype_OnUpdate $957
#cmd LNUIEventArgs_Sender $294
#cmd LNUIEventArgs_SetPrototype_OnSerialize $962
#cmd LNUIGeneralEventHandler_Create $633
#cmd LNUIEventHandler_Create $638
#cmd LNUILayoutElement_SetPrototype_OnSerialize $96D
#cmd LNUIElement_SetSize $2A6
#cmd LNUIElement_SetSizeWH $2A8
#cmd LNUIElement_SetMargin $2AB
#cmd LNUIElement_GetMargin $2AD
#cmd LNUIElement_SetPadding $2AE
#cmd LNUIElement_GetPadding $2B0
#cmd LNUIElement_SetHAlignment $2B1
#cmd LNUIElement_GetHAlignment $2B3
#cmd LNUIElement_SetVAlignment $2B4
#cmd LNUIElement_GetVAlignment $2B6
#cmd LNUIElement_SetAlignments $2B7
#cmd LNUIElement_SetPosition $2BA
#cmd LNUIElement_SetPositionXYZ $2BC
#cmd LNUIElement_GetPosition $2C0
#cmd LNUIElement_SetRotation $2C1
#cmd LNUIElement_SetEulerAngles $2C3
#cmd LNUIElement_GetRotation $2C7
#cmd LNUIElement_SetScale $2C8
#cmd LNUIElement_SetScaleS $2CA
#cmd LNUIElement_SetScaleXY $2CC
#cmd LNUIElement_GetScale $2CF
#cmd LNUIElement_SetCenterPoint $2D0
#cmd LNUIElement_SetCenterPointXYZ $2D2
#cmd LNUIElement_GetCenterPoint $2D6
#cmd LNUIElement_SetEnabled $2D7
#cmd LNUIElement_IsEnabled $2D9
#cmd LNUIElement_SetData $2DA
#cmd LNUIElement_GetData $2DC
#cmd LNUIElement_SetOpacity $2DD
#cmd LNUIElement_GetOpacity $2DF
#cmd LNUIElement_AddChild $2E0
#cmd LNUIElement_SetPrototype_OnSerialize $978
#cmd LNUITextBlock_Create $2E3
#cmd LNUITextBlock_CreateWithText $2E4
#cmd LNUITextBlock_SetPrototype_OnSerialize $983
#cmd LNUISprite_Create $2F1
#cmd LNUISprite_CreateWithTexture $2F2
#cmd LNUISprite_SetTexture $2E7
#cmd LNUISprite_SetSourceRect $2E9
#cmd LNUISprite_SetSourceRectXYWH $2EB
#cmd LNUISprite_GetSourceRect $2F0
#cmd LNUISprite_SetPrototype_OnSerialize $98E
#cmd LNUIIcon_LoadFontIcon $2F5
#cmd LNUIIcon_LoadFontIconWithNameSize $2F7
#cmd LNUIIcon_LoadFontIconWithNameSizeColor $2FA
#cmd LNUIIcon_SetPrototype_OnSerialize $999
#cmd LNUI_Add $2FF
#cmd LNUI_Remove $301
#cmd LNUILayoutPanel_SetPrototype_OnSerialize $9A4
#cmd LNUIBoxLayout_Create $308
#cmd LNUIBoxLayout_SetOrientation $305
#cmd LNUIBoxLayout_GetOrientation $307
#cmd LNUIBoxLayout_SetPrototype_OnSerialize $9AF
#cmd LNUIGridLayout_Create $318
#cmd LNUIGridLayout_SetColumnCount $30A
#cmd LNUIGridLayout_SetRow $30C
#cmd LNUIGridLayout_SetColumn $30F
#cmd LNUIGridLayout_SetPlacement $312
#cmd LNUIGridLayout_SetPrototype_OnSerialize $9BA
#cmd LNUIControl_SetPrototype_OnSerialize $9C5
#cmd LNUIButtonBase_SetText $31B
#cmd LNUIButtonBase_SetPrototype_OnSerialize $9D0
#cmd LNUIButton_Create $31E
#cmd LNUIButton_CreateWithText $31F
#cmd LNUIButton_ConnectOnClicked $321
#cmd LNUIButton_SetPrototype_OnSerialize $9DB
#cmd LNUIWindow_Create $324
#cmd LNUIWindow_SetPrototype_OnSerialize $9E6
#cmd LNUIListItem_ConnectOnSubmit $329
#cmd LNUIListItem_SetPrototype_OnSerialize $9F1
#cmd LNUIListItemsControl_SetItemsLayoutPanel $32C
#cmd LNUIListItemsControl_SetSubmitMode $32E
#cmd LNUIListItemsControl_GetSubmitMode $330
#cmd LNUIListItemsControl_SetPrototype_OnSerialize $9FC
#cmd LNUIListBoxItem_Create $332
#cmd LNUIListBoxItem_SetPrototype_OnSerialize $A07
#cmd LNUIListBox_Create $337
#cmd LNUIListBox_AddItem $335
#cmd LNUIListBox_SetPrototype_OnSerialize $A12
#cmd LNInput_IsPressed $339
#cmd LNInput_IsTriggered $33B
#cmd LNInput_IsTriggeredOff $33D
#cmd LNInput_IsRepeated $33F
#cmd LNInput_GetAxisValue $341
#cmd LNInput_ClearAllBindings $343
#cmd LNMouse_Pressed $345
#cmd LNMouse_Triggered $347
#cmd LNMouse_TriggeredOff $349
#cmd LNMouse_Repeated $34B
#cmd LNMouse_Position $34D
#cmd LNInterpreterCommand_Code $34F
#cmd LNInterpreterCommand_ParamsCount $350
#cmd LNInterpreterCommand_Param $351
#cmd LNInterpreterCommand_SetPrototype_OnSerialize $A1D
#cmd LNInterpreterCommandList_Create $368
#cmd LNInterpreterCommandList_AddCommand $354
#cmd LNInterpreterCommandList_AddCommand1 $356
#cmd LNInterpreterCommandList_AddCommand2 $359
#cmd LNInterpreterCommandList_AddCommand3 $35D
#cmd LNInterpreterCommandList_AddCommand4 $362
#cmd LNInterpreterCommandList_SetPrototype_OnSerialize $A28
#cmd LNInterpreterCommandDelegate_Create $6C1
#cmd LNInterpreter_Create $37C
#cmd LNInterpreter_Clear $36D
#cmd LNInterpreter_Run $36E
#cmd LNInterpreter_IsRunning $370
#cmd LNInterpreter_Update $371
#cmd LNInterpreter_Terminate $372
#cmd LNInterpreter_RegisterCommandHandler $373
#cmd LNInterpreter_SetWaitMode $376
#cmd LNInterpreter_GetWaitMode $378
#cmd LNInterpreter_SetWaitCount $379
#cmd LNInterpreter_GetWaitCount $37B
#cmd LNInterpreter_SetPrototype_OnSerialize $A33
#cmd LNInterpreter_SetPrototype_OnUpdateWait $A3F
#cmd LNEngineSettings_SetMainWindowSize $37F
#cmd LNEngineSettings_SetMainWorldViewSize $382
#cmd LNEngineSettings_SetMainWindowTitle $385
#cmd LNEngineSettings_AddAssetDirectory $387
#cmd LNEngineSettings_AddAssetArchive $389
#cmd LNEngineSettings_SetFrameRate $38C
#cmd LNEngineSettings_SetDefaultUITheme $38E
#cmd LNEngineSettings_SetDebugToolEnabled $390
#cmd LNEngineSettings_SetEngineLogEnabled $392
#cmd LNEngineSettings_SetEngineLogFilePath $394
#cmd LNEngine_Initialize $397
#cmd LNEngine_Finalize $398
#cmd LNEngine_Update $399
#cmd LNEngine_Run $39A
#cmd LNEngine_Time $39C
#cmd LNEngine_GetCamera $39D
#cmd LNEngine_GetMainLight $39E
#cmd LNEngine_GetRenderView $39F
#cmd LNApplication_Create $3A4
#cmd LNApplication_OnInit $3A1
#cmd LNApplication_OnUpdate $3A2
#cmd LNApplication_World $3A3
#cmd LNApplication_SetPrototype_OnSerialize $A4A
#cmd LNApplication_SetPrototype_OnInit $A55
#cmd LNApplication_SetPrototype_OnUpdate $A60
#cmd LNDebug_SetGuideGridEnabled $3A6
#cmd LNDebug_SetPhysicsDebugDrawEnabled $3A8
#cmd LNDebug_Print $3AA
#cmd LNDebug_PrintWithTime $3AC
#cmd LNDebug_PrintWithTimeAndColor $3AF
#cmd LNObjectSerializeHandler_Create $6ED
#cmd LNEventConnectionSerializeHandler_Create $6F8
#cmd LNVariantSerializeHandler_Create $703
#cmd LNZVTestClass1SerializeHandler_Create $70E
#cmd LNZVTestEventArgs1SerializeHandler_Create $719
#cmd LNSerializer2SerializeHandler_Create $724
#cmd LNAssetModelSerializeHandler_Create $72F
#cmd LNTextureSerializeHandler_Create $73A
#cmd LNTexture2DSerializeHandler_Create $745
#cmd LNRenderViewSerializeHandler_Create $750
#cmd LNSkinnedMeshModelSerializeHandler_Create $75B
#cmd LNAnimationControllerSerializeHandler_Create $766
#cmd LNCollisionShapeSerializeHandler_Create $771
#cmd LNBoxCollisionShapeSerializeHandler_Create $77C
#cmd LNAnimationClipSerializeHandler_Create $787
#cmd LNAnimationStateSerializeHandler_Create $792
#cmd LNComponentSerializeHandler_Create $79D
#cmd LNVisualComponentSerializeHandler_Create $7A8
#cmd LNSpriteComponentSerializeHandler_Create $7B3
#cmd LNCharacterControllerSerializeHandler_Create $7BE
#cmd LNWorldSerializeHandler_Create $7C9
#cmd LNComponentListSerializeHandler_Create $7D4
#cmd LNWorldObjectSerializeHandler_Create $7DF
#cmd LNWorldObjectUpdateHandler_Create $7EA
#cmd LNVisualObjectSerializeHandler_Create $7F5
#cmd LNVisualObjectUpdateHandler_Create $800
#cmd LNCameraSerializeHandler_Create $80B
#cmd LNCameraUpdateHandler_Create $816
#cmd LNEnvironmentLightSerializeHandler_Create $821
#cmd LNEnvironmentLightUpdateHandler_Create $82C
#cmd LNDirectionalLightSerializeHandler_Create $837
#cmd LNDirectionalLightUpdateHandler_Create $842
#cmd LNPointLightSerializeHandler_Create $84D
#cmd LNPointLightUpdateHandler_Create $858
#cmd LNSpotLightSerializeHandler_Create $863
#cmd LNSpotLightUpdateHandler_Create $86E
#cmd LNSpriteSerializeHandler_Create $879
#cmd LNSpriteUpdateHandler_Create $884
#cmd LNCameraOrbitControlComponentSerializeHandler_Create $88F
#cmd LNRaycasterSerializeHandler_Create $89A
#cmd LNRaycastResultSerializeHandler_Create $8A5
#cmd LNWorldRenderViewSerializeHandler_Create $8B0
#cmd LNBoxMeshSerializeHandler_Create $8BB
#cmd LNBoxMeshUpdateHandler_Create $8C6
#cmd LNPlaneMeshSerializeHandler_Create $8D1
#cmd LNPlaneMeshUpdateHandler_Create $8DC
#cmd LNStaticMeshSerializeHandler_Create $8E7
#cmd LNStaticMeshUpdateHandler_Create $8F2
#cmd LNSkinnedMeshComponentSerializeHandler_Create $8FD
#cmd LNCollisionSerializeHandler_Create $908
#cmd LNTriggerBodyComponentSerializeHandler_Create $913
#cmd LNLevelSerializeHandler_Create $91E
#cmd LNLevelStartHandler_Create $929
#cmd LNLevelStopHandler_Create $934
#cmd LNLevelPauseHandler_Create $93F
#cmd LNLevelResumeHandler_Create $94A
#cmd LNLevelUpdateHandler_Create $955
#cmd LNUIEventArgsSerializeHandler_Create $960
#cmd LNUILayoutElementSerializeHandler_Create $96B
#cmd LNUIElementSerializeHandler_Create $976
#cmd LNUITextBlockSerializeHandler_Create $981
#cmd LNUISpriteSerializeHandler_Create $98C
#cmd LNUIIconSerializeHandler_Create $997
#cmd LNUILayoutPanelSerializeHandler_Create $9A2
#cmd LNUIBoxLayoutSerializeHandler_Create $9AD
#cmd LNUIGridLayoutSerializeHandler_Create $9B8
#cmd LNUIControlSerializeHandler_Create $9C3
#cmd LNUIButtonBaseSerializeHandler_Create $9CE
#cmd LNUIButtonSerializeHandler_Create $9D9
#cmd LNUIWindowSerializeHandler_Create $9E4
#cmd LNUIListItemSerializeHandler_Create $9EF
#cmd LNUIListItemsControlSerializeHandler_Create $9FA
#cmd LNUIListBoxItemSerializeHandler_Create $A05
#cmd LNUIListBoxSerializeHandler_Create $A10
#cmd LNInterpreterCommandSerializeHandler_Create $A1B
#cmd LNInterpreterCommandListSerializeHandler_Create $A26
#cmd LNInterpreterSerializeHandler_Create $A31
#cmd LNInterpreterUpdateWaitHandler_Create $A3D
#cmd LNApplicationSerializeHandler_Create $A48
#cmd LNApplicationInitHandler_Create $A53
#cmd LNApplicationUpdateHandler_Create $A5E



#cmd ln_args $1
#cmd ln_set_args $2

#endif // __lumino__
