
#ifndef __lumino__
#define __lumino__

#ifdef LUMINO_DEBUG
    #regcmd "_hsp3cmdinit@4","LuminoHSPd.dll", 6
#else
    #regcmd "_hsp3cmdinit@4","LuminoHSP.dll", 6
#endif

#const global LN_TRUE 1
#const global LN_FALSE 0
#const global LN_NULL_HANDLE 0

#const global LN_MOUSE_BUTTONS_NONE 0
#const global LN_MOUSE_BUTTONS_LEFT 1
#const global LN_MOUSE_BUTTONS_RIGHT 2
#const global LN_MOUSE_BUTTONS_MIDDLE 3
#const global LN_MOUSE_BUTTONS_X1 4
#const global LN_MOUSE_BUTTONS_X2 5
#const global LN_PIXEL_FORMAT_UNKNOWN 0
#const global LN_PIXEL_FORMAT_A8 1
#const global LN_PIXEL_FORMAT_RGBA8 2
#const global LN_PIXEL_FORMAT_RGB8 3
#const global LN_PIXEL_FORMAT_RGBA32F 4
#const global LN_PIXEL_FORMAT_R32S 5
#const global LN_TEXTURE_FORMAT_UNKNOWN 0
#const global LN_TEXTURE_FORMAT_RGBA8 1
#const global LN_TEXTURE_FORMAT_RGB8 2
#const global LN_TEXTURE_FORMAT_RGBA16F 3
#const global LN_TEXTURE_FORMAT_RGBA32F 4
#const global LN_TEXTURE_FORMAT_R16F 5
#const global LN_TEXTURE_FORMAT_R32F 6
#const global LN_TEXTURE_FORMAT_R32S 7
#const global LN_DEPTH_BUFFER_FORMAT_D24S8 0
#const global LN_SCENE_CLEAR_MODE_NONE 0
#const global LN_SCENE_CLEAR_MODE_COLOR_AND_DEPTH 1
#const global LN_SCENE_CLEAR_MODE_SKY 2
#const global LN_SCENE_CLEAR_MODE_SKY0 3
#const global LN_SCENE_CLEAR_MODE_SKY_DOME 4
#const global LN_HIERARCHICAL_ANIMATION_MODE_ALLOW_TRANSLATION_ONLY_ROOT 0
#const global LN_HIERARCHICAL_ANIMATION_MODE_ALLOW_TRANSLATION_ONLY_ROOT_Y 1
#const global LN_HIERARCHICAL_ANIMATION_MODE_ALLOW_TRANSLATION 2
#const global LN_HIERARCHICAL_ANIMATION_MODE_DISABLE_TRANSLATION 3
#const global LN_LEVEL_TRANSITION_EFFECT_MODE_NONE 0
#const global LN_LEVEL_TRANSITION_EFFECT_MODE_FADE_IN_OUT 1
#const global LN_LEVEL_TRANSITION_EFFECT_MODE_CROSS_FADE 2
#const global LN_UILAYOUT_ORIENTATION_HORIZONTAL 0
#const global LN_UILAYOUT_ORIENTATION_VERTICAL 1
#const global LN_UILAYOUT_ORIENTATION_REVERSE_HORIZONTAL 2
#const global LN_UILAYOUT_ORIENTATION_REVERSE_VERTICAL 3
#const global LN_UIVALIGNMENT_TOP 0
#const global LN_UIVALIGNMENT_CENTER 1
#const global LN_UIVALIGNMENT_BOTTOM 2
#const global LN_UIVALIGNMENT_STRETCH 3
#const global LN_UIHALIGNMENT_LEFT 0
#const global LN_UIHALIGNMENT_CENTER 1
#const global LN_UIHALIGNMENT_RIGHT 2
#const global LN_UIHALIGNMENT_STRETCH 3
#const global LN_UILIST_SUBMIT_MODE_SINGLE 0
#const global LN_UILIST_SUBMIT_MODE_DOUBLE 1

#cmd LNVector3 $2B
#cmd LNVector3_GetX $3CB
#cmd LNVector3_SetX $3CD
#cmd LNVector3_GetY $3CE
#cmd LNVector3_SetY $3D0
#cmd LNVector3_GetZ $3D1
#cmd LNVector3_SetZ $3D3
#cmd LNVector3_SetZeros $2F
#cmd LNVector3_Set $30
#cmd LNVector3_Get $34
#cmd LNVector3_Length $38
#cmd LNVector3_LengthSquared $39
#cmd LNVector3_MutatingNormalize $3A
#cmd LNVector3_NormalizeXYZ $3B
#cmd LNVector3_Normalize $3F
#cmd LNVector4 $41
#cmd LNVector4_GetX $3EA
#cmd LNVector4_SetX $3EC
#cmd LNVector4_GetY $3ED
#cmd LNVector4_SetY $3EF
#cmd LNVector4_GetZ $3F0
#cmd LNVector4_SetZ $3F2
#cmd LNVector4_GetW $3F3
#cmd LNVector4_SetW $3F5
#cmd LNVector4_SetZeros $46
#cmd LNVector4_Set $47
#cmd LNQuaternion $4C
#cmd LNQuaternion_GetX $408
#cmd LNQuaternion_SetX $40A
#cmd LNQuaternion_GetY $40B
#cmd LNQuaternion_SetY $40D
#cmd LNQuaternion_GetZ $40E
#cmd LNQuaternion_SetZ $410
#cmd LNQuaternion_GetW $411
#cmd LNQuaternion_SetW $413
#cmd LNQuaternion_SetZeros $51
#cmd LNQuaternion_Set $52
#cmd LNQuaternion_SetFromAxis $57
#cmd LNMatrix $5A
#cmd LNMatrix_GetRow0 $427
#cmd LNMatrix_SetRow0 $429
#cmd LNMatrix_GetRow1 $42A
#cmd LNMatrix_SetRow1 $42C
#cmd LNMatrix_GetRow2 $42D
#cmd LNMatrix_SetRow2 $42F
#cmd LNMatrix_GetRow3 $430
#cmd LNMatrix_SetRow3 $432
#cmd LNMatrix_SetZeros $5F
#cmd LNMatrix_Set $60
#cmd LNColor $F9
#cmd LNColor_GetR $4B0
#cmd LNColor_SetR $4B2
#cmd LNColor_GetG $4B3
#cmd LNColor_SetG $4B5
#cmd LNColor_GetB $4B6
#cmd LNColor_SetB $4B8
#cmd LNColor_GetA $4B9
#cmd LNColor_SetA $4BB
#cmd LNColor_SetZeros $FE
#cmd LNColor_Set $FF
#cmd LNPoint $104
#cmd LNPoint_GetX $4CF
#cmd LNPoint_SetX $4D1
#cmd LNPoint_GetY $4D2
#cmd LNPoint_SetY $4D4
#cmd LNPoint_SetZeros $107
#cmd LNPoint_Set $108
#cmd LNSize $10B
#cmd LNSize_GetWidth $4DF
#cmd LNSize_SetWidth $4E1
#cmd LNSize_GetHeight $4E2
#cmd LNSize_SetHeight $4E4
#cmd LNSize_SetZeros $10E
#cmd LNSize_Set $10F
#cmd LNRect $112
#cmd LNRect_GetX $4EF
#cmd LNRect_SetX $4F1
#cmd LNRect_GetY $4F2
#cmd LNRect_SetY $4F4
#cmd LNRect_GetWidth $4F5
#cmd LNRect_SetWidth $4F7
#cmd LNRect_GetHeight $4F8
#cmd LNRect_SetHeight $4FA
#cmd LNRect_SetZeros $117
#cmd LNRect_Set $118
#cmd LNRect_GetLeft $11D
#cmd LNRect_SetSize $11E
#cmd LNRect_GetSize $120
#cmd LNThickness $121
#cmd LNThickness_GetLeft $513
#cmd LNThickness_SetLeft $515
#cmd LNThickness_GetTop $516
#cmd LNThickness_SetTop $518
#cmd LNThickness_GetRight $519
#cmd LNThickness_SetRight $51B
#cmd LNThickness_GetBottom $51C
#cmd LNThickness_SetBottom $51E
#cmd LNThickness_SetZeros $126
#cmd LNThickness_Set $127

#cmd LNObject_Release $74
#cmd LNObject_Retain $75
#cmd LNObject_GetReferenceCount $76
#cmd LNObject_SetPrototype_OnSerialize $717
#cmd LNEventConnection_SetPrototype_OnSerialize $722
#cmd LNPromiseFailureDelegate_Create $44D
#cmd LNVariant_Create $7B
#cmd LNVariant_SetInt $7C
#cmd LNVariant_GetInt $7E
#cmd LNVariant_SetPrototype_OnSerialize $72D
#cmd LNZVTestDelegate1_Create $456
#cmd LNZVTestDelegate2_Create $45C
#cmd LNZVTestDelegate3_Create $461
#cmd LNZVTestEventHandler1_Create $466
#cmd LNZVTestEventHandler2_Create $46B
#cmd LNZVTestPromise1_ThenWith $46E
#cmd LNZVTestPromise1_CatchWith $470
#cmd LNZVTestPromise2_ThenWith $474
#cmd LNZVTestPromise2_CatchWith $476
#cmd LNZVTestClass1_Create $A7
#cmd LNZVTestClass1_SetTestDelegate1 $91
#cmd LNZVTestClass1_SetTestDelegate2 $93
#cmd LNZVTestClass1_SetTestDelegate3 $95
#cmd LNZVTestClass1_CallTestDelegate1 $97
#cmd LNZVTestClass1_CallTestDelegate2 $99
#cmd LNZVTestClass1_CallTestDelegate3 $9C
#cmd LNZVTestClass1_LoadAsync $9D
#cmd LNZVTestClass1_ExecuteAsync $9F
#cmd LNZVTestClass1_GetFilePath $A0
#cmd LNZVTestClass1_ConnectOnEvent1 $A1
#cmd LNZVTestClass1_RaiseEvent1 $A3
#cmd LNZVTestClass1_ConnectOnEvent2 $A4
#cmd LNZVTestClass1_RaiseEvent2 $A6
#cmd LNZVTestClass1_SetPrototype_OnSerialize $738
#cmd LNZVTestEventArgs1_Create $AA
#cmd LNZVTestEventArgs1_CreateWithValue $AB
#cmd LNZVTestEventArgs1_GetValue $A9
#cmd LNZVTestEventArgs1_SetPrototype_OnSerialize $743
#cmd LNSerializer2_SetPrototype_OnSerialize $74E
#cmd LNAssetModel_Create $B7
#cmd LNAssetModel_Target $B6
#cmd LNAssetModel_SetPrototype_OnSerialize $759
#cmd LNAssets_SaveAssetToLocalFile $BA
#cmd LNAssets_LoadAssetFromLocalFile $BD
#cmd LNAssets_LoadAsset $BF
#cmd LNAssets_ReloadAsset $C1
#cmd LNAudio_PlayBGM $C5
#cmd LNAudio_StopBGM $CA
#cmd LNAudio_PlayBGS $CC
#cmd LNAudio_StopBGS $D1
#cmd LNAudio_PlayME $D3
#cmd LNAudio_StopME $D7
#cmd LNAudio_PlaySE $D8
#cmd LNAudio_PlaySE3D $DC
#cmd LNAudio_StopSE $E2
#cmd LNTexture2DDelegate_Create $4A8
#cmd LNTexture2DPromise_ThenWith $4AB
#cmd LNTexture2DPromise_CatchWith $4AD
#cmd LNTexture_SetPrototype_OnSerialize $764
#cmd LNTexture2D_Create $132
#cmd LNTexture2D_CreateWithFormat $135
#cmd LNTexture2D_Load $12E
#cmd LNTexture2D_LoadEmoji $130
#cmd LNTexture2D_SetPrototype_OnSerialize $76F
#cmd LNRenderView_SetPrototype_OnSerialize $77A
#cmd LNSkinnedMeshModel_Load $141
#cmd LNSkinnedMeshModel_GetAnimationController $143
#cmd LNSkinnedMeshModel_SetPrototype_OnSerialize $785
#cmd LNAnimationController_AddClip $145
#cmd LNAnimationController_Play $147
#cmd LNAnimationController_SetPrototype_OnSerialize $790
#cmd LNCollisionShape_SetPrototype_OnSerialize $79B
#cmd LNBoxCollisionShape_Create $14C
#cmd LNBoxCollisionShape_CreateWHD $14E
#cmd LNBoxCollisionShape_SetPrototype_OnSerialize $7A6
#cmd LNAnimationClip_Load $158
#cmd LNAnimationClip_SetHierarchicalAnimationMode $15A
#cmd LNAnimationClip_HierarchicalAnimationMode $15C
#cmd LNAnimationClip_SetPrototype_OnSerialize $7B1
#cmd LNAnimationState_SetPrototype_OnSerialize $7BC
#cmd LNComponent_SetPrototype_OnSerialize $7C7
#cmd LNVisualComponent_SetVisible $160
#cmd LNVisualComponent_IsVisible $162
#cmd LNVisualComponent_SetPrototype_OnSerialize $7D2
#cmd LNSpriteComponent_SetTexture $164
#cmd LNSpriteComponent_SetPrototype_OnSerialize $7DD
#cmd LNCollisionEventHandler_Create $54C
#cmd LNCharacterController_Create $181
#cmd LNCharacterController_SetVelocity $16E
#cmd LNCharacterController_GetVelocity $170
#cmd LNCharacterController_SetInputControlEnabled $171
#cmd LNCharacterController_SetCameraControlEnabled $173
#cmd LNCharacterController_SetHeight $175
#cmd LNCharacterController_GetHeight $177
#cmd LNCharacterController_SetCameraRadius $178
#cmd LNCharacterController_GetCameraRadius $17A
#cmd LNCharacterController_SetCollisionEnter $17B
#cmd LNCharacterController_SetCollisionLeave $17D
#cmd LNCharacterController_SetCollisionStay $17F
#cmd LNCharacterController_SetPrototype_OnSerialize $7E8
#cmd LNWorld_Add $183
#cmd LNWorld_SetPrototype_OnSerialize $7F3
#cmd LNComponentList_GetLength $567
#cmd LNComponentList_GetItem $569
#cmd LNComponentList_SetPrototype_OnSerialize $7FE
#cmd LNWorldObject_Create $1B9
#cmd LNWorldObject_SetPosition $187
#cmd LNWorldObject_SetPositionXYZ $189
#cmd LNWorldObject_GetPosition $18D
#cmd LNWorldObject_SetRotationQuaternion $18E
#cmd LNWorldObject_SetRotation $190
#cmd LNWorldObject_GetRotation $194
#cmd LNWorldObject_SetScale $195
#cmd LNWorldObject_SetScaleS $197
#cmd LNWorldObject_SetScaleXYZ $199
#cmd LNWorldObject_GetScale $19D
#cmd LNWorldObject_SetCenterPoint $19E
#cmd LNWorldObject_SetCenterPointXYZ $1A0
#cmd LNWorldObject_GetCenterPoint $1A4
#cmd LNWorldObject_LookAt $1A5
#cmd LNWorldObject_LookAtXYZ $1A7
#cmd LNWorldObject_AddComponent $1AB
#cmd LNWorldObject_RemoveComponent $1AD
#cmd LNWorldObject_AddTag $1AF
#cmd LNWorldObject_RemoveTag $1B1
#cmd LNWorldObject_HasTag $1B3
#cmd LNWorldObject_Destroy $1B5
#cmd LNWorldObject_GetComponents $1B6
#cmd LNWorldObject_SetPrototype_OnSerialize $809
#cmd LNWorldObject_SetPrototype_OnUpdate $814
#cmd LNVisualObject_SetVisible $1BB
#cmd LNVisualObject_IsVisible $1BD
#cmd LNVisualObject_SetPrototype_OnSerialize $81F
#cmd LNVisualObject_SetPrototype_OnUpdate $82A
#cmd LNCamera_SetPrototype_OnSerialize $835
#cmd LNCamera_SetPrototype_OnUpdate $840
#cmd LNEnvironmentLight_SetEnabled $1C0
#cmd LNEnvironmentLight_IsEnabled $1C2
#cmd LNEnvironmentLight_SetColor $1C3
#cmd LNEnvironmentLight_GetColor $1C5
#cmd LNEnvironmentLight_SetAmbientColor $1C6
#cmd LNEnvironmentLight_GetAmbientColor $1C8
#cmd LNEnvironmentLight_GetSkyColor $1C9
#cmd LNEnvironmentLight_SetSkyColor $1CA
#cmd LNEnvironmentLight_GetGroundColor $1CC
#cmd LNEnvironmentLight_SetGroundColor $1CD
#cmd LNEnvironmentLight_SetIntensity $1CF
#cmd LNEnvironmentLight_GetIntensity $1D1
#cmd LNEnvironmentLight_SetShadowEffectiveDistance $1D2
#cmd LNEnvironmentLight_GetShadowEffectiveDistance $1D4
#cmd LNEnvironmentLight_SetShadowEffectiveDepth $1D5
#cmd LNEnvironmentLight_GetShadowEffectiveDepth $1D7
#cmd LNEnvironmentLight_SetPrototype_OnSerialize $84B
#cmd LNEnvironmentLight_SetPrototype_OnUpdate $856
#cmd LNDirectionalLight_Create $1E8
#cmd LNDirectionalLight_CreateWithColor $1E9
#cmd LNDirectionalLight_SetEnabled $1D9
#cmd LNDirectionalLight_IsEnabled $1DB
#cmd LNDirectionalLight_SetColor $1DC
#cmd LNDirectionalLight_GetColor $1DE
#cmd LNDirectionalLight_SetIntensity $1DF
#cmd LNDirectionalLight_GetIntensity $1E1
#cmd LNDirectionalLight_SetShadowEffectiveDistance $1E2
#cmd LNDirectionalLight_GetShadowEffectiveDistance $1E4
#cmd LNDirectionalLight_SetShadowEffectiveDepth $1E5
#cmd LNDirectionalLight_GetShadowEffectiveDepth $1E7
#cmd LNDirectionalLight_SetPrototype_OnSerialize $861
#cmd LNDirectionalLight_SetPrototype_OnUpdate $86C
#cmd LNPointLight_Create $1FB
#cmd LNPointLight_CreateWithColorAndRange $1FC
#cmd LNPointLight_SetEnabled $1EC
#cmd LNPointLight_IsEnabled $1EE
#cmd LNPointLight_SetColor $1EF
#cmd LNPointLight_GetColor $1F1
#cmd LNPointLight_SetIntensity $1F2
#cmd LNPointLight_GetIntensity $1F4
#cmd LNPointLight_SetRange $1F5
#cmd LNPointLight_GetRange $1F7
#cmd LNPointLight_SetAttenuation $1F8
#cmd LNPointLight_GetAttenuation $1FA
#cmd LNPointLight_SetPrototype_OnSerialize $877
#cmd LNPointLight_SetPrototype_OnUpdate $882
#cmd LNSpotLight_Create $215
#cmd LNSpotLight_CreateWithColorAndRange $216
#cmd LNSpotLight_SetEnabled $200
#cmd LNSpotLight_IsEnabled $202
#cmd LNSpotLight_SetColor $203
#cmd LNSpotLight_GetColor $205
#cmd LNSpotLight_SetIntensity $206
#cmd LNSpotLight_GetIntensity $208
#cmd LNSpotLight_SetRange $209
#cmd LNSpotLight_GetRange $20B
#cmd LNSpotLight_SetAttenuation $20C
#cmd LNSpotLight_GetAttenuation $20E
#cmd LNSpotLight_SetAngle $20F
#cmd LNSpotLight_GetAngle $211
#cmd LNSpotLight_SetPenumbra $212
#cmd LNSpotLight_GetPenumbra $214
#cmd LNSpotLight_SetPrototype_OnSerialize $88D
#cmd LNSpotLight_SetPrototype_OnUpdate $898
#cmd LNTestDelegate_Create $60D
#cmd LNSprite_Create $22C
#cmd LNSprite_CreateWithTexture $22D
#cmd LNSprite_CreateWithTextureAndSize $22F
#cmd LNSprite_SetTexture $21E
#cmd LNSprite_SetSize $220
#cmd LNSprite_SetSizeWH $222
#cmd LNSprite_SetSourceRectXYWH $225
#cmd LNSprite_SetCallerTest $22A
#cmd LNSprite_SetPrototype_OnSerialize $8A3
#cmd LNSprite_SetPrototype_OnUpdate $8AE
#cmd LNCameraOrbitControlComponent_Create $234
#cmd LNCameraOrbitControlComponent_SetPrototype_OnSerialize $8B9
#cmd LNRaycaster_FromScreen $236
#cmd LNRaycaster_IntersectPlane $238
#cmd LNRaycaster_SetPrototype_OnSerialize $8C4
#cmd LNRaycastResult_GetPoint $23D
#cmd LNRaycastResult_SetPrototype_OnSerialize $8CF
#cmd LNWorldRenderView_SetGuideGridEnabled $23F
#cmd LNWorldRenderView_GetGuideGridEnabled $241
#cmd LNWorldRenderView_SetPrototype_OnSerialize $8DA
#cmd LNBoxMesh_Create $243
#cmd LNBoxMesh_SetPrototype_OnSerialize $8E5
#cmd LNBoxMesh_SetPrototype_OnUpdate $8F0
#cmd LNPlaneMesh_Create $245
#cmd LNPlaneMesh_SetPrototype_OnSerialize $8FB
#cmd LNPlaneMesh_SetPrototype_OnUpdate $906
#cmd LNStaticMesh_Load $247
#cmd LNStaticMesh_MakeCollisionBody $249
#cmd LNStaticMesh_SetPrototype_OnSerialize $911
#cmd LNStaticMesh_SetPrototype_OnUpdate $91C
#cmd LNSkinnedMeshComponent_Create $24E
#cmd LNSkinnedMeshComponent_SetModel $24C
#cmd LNSkinnedMeshComponent_SetPrototype_OnSerialize $927
#cmd LNCollision_GetWorldObject $250
#cmd LNCollision_SetPrototype_OnSerialize $932
#cmd LNTriggerBodyComponent_Create $254
#cmd LNTriggerBodyComponent_AddCollisionShape $252
#cmd LNTriggerBodyComponent_SetPrototype_OnSerialize $93D
#cmd LNScene_SetClearMode $256
#cmd LNScene_SetSkyColor $258
#cmd LNScene_SetSkyHorizonColor $25A
#cmd LNScene_SetSkyCloudColor $25C
#cmd LNScene_SetSkyOverlayColor $25E
#cmd LNScene_GotoLevel $260
#cmd LNScene_CallLevel $263
#cmd LNScene_ReturnLevel $266
#cmd LNScene_ActiveLevel $268
#cmd LNScene_IsTransitionEffectRunning $269
#cmd LNScene_SetTransitionEffectMode $26A
#cmd LNScene_TransitionEffectMode $26C
#cmd LNScene_SetTransitionDuration $26D
#cmd LNScene_TransitionDuration $26F
#cmd LNScene_SetTransitionEffectColor $270
#cmd LNScene_TransitionEffectColor $272
#cmd LNScene_SetTransitionEffectMaskTexture $273
#cmd LNScene_TransitionEffectMaskTexture $275
#cmd LNScene_SetTransitionEffectVague $276
#cmd LNScene_TransitionEffectVague $278
#cmd LNScene_StartFadeOut $279
#cmd LNScene_StartFadeIn $27A
#cmd LNScene_SetScreenBlendColor $27B
#cmd LNScene_ScreenBlendColor $27D
#cmd LNScene_SetAntialiasEnabled $27E
#cmd LNScene_IsAntialiasEnabled $280
#cmd LNScene_SetSSREnabled $281
#cmd LNScene_IsSSREnabled $283
#cmd LNScene_SetSSAOEnabled $284
#cmd LNScene_IsSSAOEnabled $286
#cmd LNScene_SetBloomEnabled $287
#cmd LNScene_IsBloomEnabled $289
#cmd LNScene_SetDOFEnabled $28A
#cmd LNScene_IsDOFEnabled $28C
#cmd LNScene_SetTonemapEnabled $28D
#cmd LNScene_IsTonemapEnabled $28F
#cmd LNScene_SetVignetteEnabled $290
#cmd LNScene_IsVignetteEnabled $292
#cmd LNScene_SetGammaEnabled $293
#cmd LNScene_IsGammaEnabled $295
#cmd LNLevel_Create $2A5
#cmd LNLevel_AddObject $297
#cmd LNLevel_RemoveObject $299
#cmd LNLevel_AddSubLevel $29B
#cmd LNLevel_RemoveSubLevel $29D
#cmd LNLevel_RemoveAllSubLevels $29F
#cmd LNLevel_SetPrototype_OnSerialize $948
#cmd LNLevel_SetPrototype_OnStart $953
#cmd LNLevel_SetPrototype_OnStop $95E
#cmd LNLevel_SetPrototype_OnPause $969
#cmd LNLevel_SetPrototype_OnResume $974
#cmd LNLevel_SetPrototype_OnUpdate $97F
#cmd LNUIEventArgs_Sender $2AC
#cmd LNUIEventArgs_SetPrototype_OnSerialize $98A
#cmd LNUIGeneralEventHandler_Create $65B
#cmd LNUIEventHandler_Create $660
#cmd LNUILayoutElement_SetPrototype_OnSerialize $995
#cmd LNUIElement_SetSize $2BE
#cmd LNUIElement_SetSizeWH $2C0
#cmd LNUIElement_SetMargin $2C3
#cmd LNUIElement_GetMargin $2C5
#cmd LNUIElement_SetPadding $2C6
#cmd LNUIElement_GetPadding $2C8
#cmd LNUIElement_SetHAlignment $2C9
#cmd LNUIElement_GetHAlignment $2CB
#cmd LNUIElement_SetVAlignment $2CC
#cmd LNUIElement_GetVAlignment $2CE
#cmd LNUIElement_SetAlignments $2CF
#cmd LNUIElement_SetPosition $2D2
#cmd LNUIElement_SetPositionXYZ $2D4
#cmd LNUIElement_GetPosition $2D8
#cmd LNUIElement_SetRotation $2D9
#cmd LNUIElement_SetEulerAngles $2DB
#cmd LNUIElement_GetRotation $2DF
#cmd LNUIElement_SetScale $2E0
#cmd LNUIElement_SetScaleS $2E2
#cmd LNUIElement_SetScaleXY $2E4
#cmd LNUIElement_GetScale $2E7
#cmd LNUIElement_SetCenterPoint $2E8
#cmd LNUIElement_SetCenterPointXYZ $2EA
#cmd LNUIElement_GetCenterPoint $2EE
#cmd LNUIElement_SetEnabled $2EF
#cmd LNUIElement_IsEnabled $2F1
#cmd LNUIElement_SetData $2F2
#cmd LNUIElement_GetData $2F4
#cmd LNUIElement_SetOpacity $2F5
#cmd LNUIElement_GetOpacity $2F7
#cmd LNUIElement_AddChild $2F8
#cmd LNUIElement_SetPrototype_OnSerialize $9A0
#cmd LNUITextBlock_Create $2FB
#cmd LNUITextBlock_CreateWithText $2FC
#cmd LNUITextBlock_SetPrototype_OnSerialize $9AB
#cmd LNUISprite_Create $309
#cmd LNUISprite_CreateWithTexture $30A
#cmd LNUISprite_SetTexture $2FF
#cmd LNUISprite_SetSourceRect $301
#cmd LNUISprite_SetSourceRectXYWH $303
#cmd LNUISprite_GetSourceRect $308
#cmd LNUISprite_SetPrototype_OnSerialize $9B6
#cmd LNUIIcon_LoadFontIcon $30D
#cmd LNUIIcon_LoadFontIconWithNameSize $30F
#cmd LNUIIcon_LoadFontIconWithNameSizeColor $312
#cmd LNUIIcon_SetPrototype_OnSerialize $9C1
#cmd LNUI_Add $317
#cmd LNUI_Remove $319
#cmd LNUILayoutPanel_SetPrototype_OnSerialize $9CC
#cmd LNUIBoxLayout_Create $320
#cmd LNUIBoxLayout_SetOrientation $31D
#cmd LNUIBoxLayout_GetOrientation $31F
#cmd LNUIBoxLayout_SetPrototype_OnSerialize $9D7
#cmd LNUIGridLayout_Create $330
#cmd LNUIGridLayout_SetColumnCount $322
#cmd LNUIGridLayout_SetRow $324
#cmd LNUIGridLayout_SetColumn $327
#cmd LNUIGridLayout_SetPlacement $32A
#cmd LNUIGridLayout_SetPrototype_OnSerialize $9E2
#cmd LNUIControl_SetPrototype_OnSerialize $9ED
#cmd LNUIButtonBase_SetText $333
#cmd LNUIButtonBase_SetPrototype_OnSerialize $9F8
#cmd LNUIButton_Create $336
#cmd LNUIButton_CreateWithText $337
#cmd LNUIButton_ConnectOnClicked $339
#cmd LNUIButton_SetPrototype_OnSerialize $A03
#cmd LNUIWindow_Create $33C
#cmd LNUIWindow_SetPrototype_OnSerialize $A0E
#cmd LNUIListItem_ConnectOnSubmit $341
#cmd LNUIListItem_SetPrototype_OnSerialize $A19
#cmd LNUIListItemsControl_SetItemsLayoutPanel $344
#cmd LNUIListItemsControl_SetSubmitMode $346
#cmd LNUIListItemsControl_GetSubmitMode $348
#cmd LNUIListItemsControl_SetPrototype_OnSerialize $A24
#cmd LNUIListBoxItem_Create $34A
#cmd LNUIListBoxItem_SetPrototype_OnSerialize $A2F
#cmd LNUIListBox_Create $34F
#cmd LNUIListBox_AddItem $34D
#cmd LNUIListBox_SetPrototype_OnSerialize $A3A
#cmd LNInput_IsPressed $351
#cmd LNInput_IsTriggered $353
#cmd LNInput_IsTriggeredOff $355
#cmd LNInput_IsRepeated $357
#cmd LNInput_GetAxisValue $359
#cmd LNInput_ClearAllBindings $35B
#cmd LNMouse_Pressed $35D
#cmd LNMouse_Triggered $35F
#cmd LNMouse_TriggeredOff $361
#cmd LNMouse_Repeated $363
#cmd LNMouse_Position $365
#cmd LNInterpreterCommand_Code $367
#cmd LNInterpreterCommand_ParamsCount $368
#cmd LNInterpreterCommand_Param $369
#cmd LNInterpreterCommand_SetPrototype_OnSerialize $A45
#cmd LNInterpreterCommandList_Create $380
#cmd LNInterpreterCommandList_AddCommand $36C
#cmd LNInterpreterCommandList_AddCommand1 $36E
#cmd LNInterpreterCommandList_AddCommand2 $371
#cmd LNInterpreterCommandList_AddCommand3 $375
#cmd LNInterpreterCommandList_AddCommand4 $37A
#cmd LNInterpreterCommandList_SetPrototype_OnSerialize $A50
#cmd LNInterpreterCommandDelegate_Create $6E9
#cmd LNInterpreter_Create $394
#cmd LNInterpreter_Clear $385
#cmd LNInterpreter_Run $386
#cmd LNInterpreter_IsRunning $388
#cmd LNInterpreter_Update $389
#cmd LNInterpreter_Terminate $38A
#cmd LNInterpreter_RegisterCommandHandler $38B
#cmd LNInterpreter_SetWaitMode $38E
#cmd LNInterpreter_GetWaitMode $390
#cmd LNInterpreter_SetWaitCount $391
#cmd LNInterpreter_GetWaitCount $393
#cmd LNInterpreter_SetPrototype_OnSerialize $A5B
#cmd LNInterpreter_SetPrototype_OnUpdateWait $A67
#cmd LNEngineSettings_SetMainWindowSize $397
#cmd LNEngineSettings_SetMainWorldViewSize $39A
#cmd LNEngineSettings_SetMainWindowTitle $39D
#cmd LNEngineSettings_AddAssetDirectory $39F
#cmd LNEngineSettings_AddAssetArchive $3A1
#cmd LNEngineSettings_SetFrameRate $3A4
#cmd LNEngineSettings_SetDefaultUITheme $3A6
#cmd LNEngineSettings_SetDebugToolEnabled $3A8
#cmd LNEngineSettings_SetEngineLogEnabled $3AA
#cmd LNEngineSettings_SetEngineLogFilePath $3AC
#cmd LNEngine_Initialize $3AF
#cmd LNEngine_Finalize $3B0
#cmd LNEngine_Update $3B1
#cmd LNEngine_Run $3B2
#cmd LNEngine_Time $3B4
#cmd LNEngine_GetCamera $3B5
#cmd LNEngine_GetMainLight $3B6
#cmd LNEngine_GetRenderView $3B7
#cmd LNApplication_Create $3BC
#cmd LNApplication_OnInit $3B9
#cmd LNApplication_OnUpdate $3BA
#cmd LNApplication_World $3BB
#cmd LNApplication_SetPrototype_OnSerialize $A72
#cmd LNApplication_SetPrototype_OnInit $A7D
#cmd LNApplication_SetPrototype_OnUpdate $A88
#cmd LNDebug_SetGuideGridEnabled $3BE
#cmd LNDebug_SetPhysicsDebugDrawEnabled $3C0
#cmd LNDebug_Print $3C2
#cmd LNDebug_PrintWithTime $3C4
#cmd LNDebug_PrintWithTimeAndColor $3C7
#cmd LNObjectSerializeHandler_Create $715
#cmd LNEventConnectionSerializeHandler_Create $720
#cmd LNVariantSerializeHandler_Create $72B
#cmd LNZVTestClass1SerializeHandler_Create $736
#cmd LNZVTestEventArgs1SerializeHandler_Create $741
#cmd LNSerializer2SerializeHandler_Create $74C
#cmd LNAssetModelSerializeHandler_Create $757
#cmd LNTextureSerializeHandler_Create $762
#cmd LNTexture2DSerializeHandler_Create $76D
#cmd LNRenderViewSerializeHandler_Create $778
#cmd LNSkinnedMeshModelSerializeHandler_Create $783
#cmd LNAnimationControllerSerializeHandler_Create $78E
#cmd LNCollisionShapeSerializeHandler_Create $799
#cmd LNBoxCollisionShapeSerializeHandler_Create $7A4
#cmd LNAnimationClipSerializeHandler_Create $7AF
#cmd LNAnimationStateSerializeHandler_Create $7BA
#cmd LNComponentSerializeHandler_Create $7C5
#cmd LNVisualComponentSerializeHandler_Create $7D0
#cmd LNSpriteComponentSerializeHandler_Create $7DB
#cmd LNCharacterControllerSerializeHandler_Create $7E6
#cmd LNWorldSerializeHandler_Create $7F1
#cmd LNComponentListSerializeHandler_Create $7FC
#cmd LNWorldObjectSerializeHandler_Create $807
#cmd LNWorldObjectUpdateHandler_Create $812
#cmd LNVisualObjectSerializeHandler_Create $81D
#cmd LNVisualObjectUpdateHandler_Create $828
#cmd LNCameraSerializeHandler_Create $833
#cmd LNCameraUpdateHandler_Create $83E
#cmd LNEnvironmentLightSerializeHandler_Create $849
#cmd LNEnvironmentLightUpdateHandler_Create $854
#cmd LNDirectionalLightSerializeHandler_Create $85F
#cmd LNDirectionalLightUpdateHandler_Create $86A
#cmd LNPointLightSerializeHandler_Create $875
#cmd LNPointLightUpdateHandler_Create $880
#cmd LNSpotLightSerializeHandler_Create $88B
#cmd LNSpotLightUpdateHandler_Create $896
#cmd LNSpriteSerializeHandler_Create $8A1
#cmd LNSpriteUpdateHandler_Create $8AC
#cmd LNCameraOrbitControlComponentSerializeHandler_Create $8B7
#cmd LNRaycasterSerializeHandler_Create $8C2
#cmd LNRaycastResultSerializeHandler_Create $8CD
#cmd LNWorldRenderViewSerializeHandler_Create $8D8
#cmd LNBoxMeshSerializeHandler_Create $8E3
#cmd LNBoxMeshUpdateHandler_Create $8EE
#cmd LNPlaneMeshSerializeHandler_Create $8F9
#cmd LNPlaneMeshUpdateHandler_Create $904
#cmd LNStaticMeshSerializeHandler_Create $90F
#cmd LNStaticMeshUpdateHandler_Create $91A
#cmd LNSkinnedMeshComponentSerializeHandler_Create $925
#cmd LNCollisionSerializeHandler_Create $930
#cmd LNTriggerBodyComponentSerializeHandler_Create $93B
#cmd LNLevelSerializeHandler_Create $946
#cmd LNLevelStartHandler_Create $951
#cmd LNLevelStopHandler_Create $95C
#cmd LNLevelPauseHandler_Create $967
#cmd LNLevelResumeHandler_Create $972
#cmd LNLevelUpdateHandler_Create $97D
#cmd LNUIEventArgsSerializeHandler_Create $988
#cmd LNUILayoutElementSerializeHandler_Create $993
#cmd LNUIElementSerializeHandler_Create $99E
#cmd LNUITextBlockSerializeHandler_Create $9A9
#cmd LNUISpriteSerializeHandler_Create $9B4
#cmd LNUIIconSerializeHandler_Create $9BF
#cmd LNUILayoutPanelSerializeHandler_Create $9CA
#cmd LNUIBoxLayoutSerializeHandler_Create $9D5
#cmd LNUIGridLayoutSerializeHandler_Create $9E0
#cmd LNUIControlSerializeHandler_Create $9EB
#cmd LNUIButtonBaseSerializeHandler_Create $9F6
#cmd LNUIButtonSerializeHandler_Create $A01
#cmd LNUIWindowSerializeHandler_Create $A0C
#cmd LNUIListItemSerializeHandler_Create $A17
#cmd LNUIListItemsControlSerializeHandler_Create $A22
#cmd LNUIListBoxItemSerializeHandler_Create $A2D
#cmd LNUIListBoxSerializeHandler_Create $A38
#cmd LNInterpreterCommandSerializeHandler_Create $A43
#cmd LNInterpreterCommandListSerializeHandler_Create $A4E
#cmd LNInterpreterSerializeHandler_Create $A59
#cmd LNInterpreterUpdateWaitHandler_Create $A65
#cmd LNApplicationSerializeHandler_Create $A70
#cmd LNApplicationInitHandler_Create $A7B
#cmd LNApplicationUpdateHandler_Create $A86



#cmd ln_args $1
#cmd ln_set_args $2

#endif // __lumino__
