
#ifndef __lumino__
#define __lumino__

#ifdef LUMINO_DEBUG
    #regcmd "_hsp3cmdinit@4","LuminoHSPd.dll", 6
#else
    #regcmd "_hsp3cmdinit@4","LuminoHSP.dll", 6
#endif

#const global LN_TRUE 1
#const global LN_FALSE 0
#const global LN_NULL_HANDLE 0

#const global LN_MOUSE_BUTTONS_NONE 0
#const global LN_MOUSE_BUTTONS_LEFT 1
#const global LN_MOUSE_BUTTONS_RIGHT 2
#const global LN_MOUSE_BUTTONS_MIDDLE 3
#const global LN_MOUSE_BUTTONS_X1 4
#const global LN_MOUSE_BUTTONS_X2 5
#const global LN_PIXEL_FORMAT_UNKNOWN 0
#const global LN_PIXEL_FORMAT_A8 1
#const global LN_PIXEL_FORMAT_RGBA8 2
#const global LN_PIXEL_FORMAT_RGB8 3
#const global LN_PIXEL_FORMAT_RGBA32F 4
#const global LN_PIXEL_FORMAT_R32S 5
#const global LN_TEXTURE_FORMAT_UNKNOWN 0
#const global LN_TEXTURE_FORMAT_RGBA8 1
#const global LN_TEXTURE_FORMAT_RGB8 2
#const global LN_TEXTURE_FORMAT_RGBA16F 3
#const global LN_TEXTURE_FORMAT_RGBA32F 4
#const global LN_TEXTURE_FORMAT_R16F 5
#const global LN_TEXTURE_FORMAT_R32F 6
#const global LN_TEXTURE_FORMAT_R32S 7
#const global LN_DEPTH_BUFFER_FORMAT_D24S8 0
#const global LN_SCENE_CLEAR_MODE_NONE 0
#const global LN_SCENE_CLEAR_MODE_COLOR_AND_DEPTH 1
#const global LN_SCENE_CLEAR_MODE_SKY 2
#const global LN_SCENE_CLEAR_MODE_SKY0 3
#const global LN_SCENE_CLEAR_MODE_SKY_DOME 4
#const global LN_LEVEL_TRANSITION_EFFECT_MODE_NONE 0
#const global LN_LEVEL_TRANSITION_EFFECT_MODE_FADE_IN_OUT 1
#const global LN_LEVEL_TRANSITION_EFFECT_MODE_CROSS_FADE 2
#const global LN_UILAYOUT_ORIENTATION_HORIZONTAL 0
#const global LN_UILAYOUT_ORIENTATION_VERTICAL 1
#const global LN_UILAYOUT_ORIENTATION_REVERSE_HORIZONTAL 2
#const global LN_UILAYOUT_ORIENTATION_REVERSE_VERTICAL 3
#const global LN_UIVALIGNMENT_TOP 0
#const global LN_UIVALIGNMENT_CENTER 1
#const global LN_UIVALIGNMENT_BOTTOM 2
#const global LN_UIVALIGNMENT_STRETCH 3
#const global LN_UIHALIGNMENT_LEFT 0
#const global LN_UIHALIGNMENT_CENTER 1
#const global LN_UIHALIGNMENT_RIGHT 2
#const global LN_UIHALIGNMENT_STRETCH 3
#const global LN_UILIST_SUBMIT_MODE_SINGLE 0
#const global LN_UILIST_SUBMIT_MODE_DOUBLE 1

#cmd LNVector3 $2B
#cmd LNVector3_GetX $389
#cmd LNVector3_SetX $38B
#cmd LNVector3_GetY $38C
#cmd LNVector3_SetY $38E
#cmd LNVector3_GetZ $38F
#cmd LNVector3_SetZ $391
#cmd LNVector3_SetZeros $2F
#cmd LNVector3_Set $30
#cmd LNVector3_Get $34
#cmd LNVector3_Length $38
#cmd LNVector3_LengthSquared $39
#cmd LNVector3_MutatingNormalize $3A
#cmd LNVector3_NormalizeXYZ $3B
#cmd LNVector3_Normalize $3F
#cmd LNVector4 $41
#cmd LNVector4_GetX $3A8
#cmd LNVector4_SetX $3AA
#cmd LNVector4_GetY $3AB
#cmd LNVector4_SetY $3AD
#cmd LNVector4_GetZ $3AE
#cmd LNVector4_SetZ $3B0
#cmd LNVector4_GetW $3B1
#cmd LNVector4_SetW $3B3
#cmd LNVector4_SetZeros $46
#cmd LNVector4_Set $47
#cmd LNQuaternion $4C
#cmd LNQuaternion_GetX $3C6
#cmd LNQuaternion_SetX $3C8
#cmd LNQuaternion_GetY $3C9
#cmd LNQuaternion_SetY $3CB
#cmd LNQuaternion_GetZ $3CC
#cmd LNQuaternion_SetZ $3CE
#cmd LNQuaternion_GetW $3CF
#cmd LNQuaternion_SetW $3D1
#cmd LNQuaternion_SetZeros $51
#cmd LNQuaternion_Set $52
#cmd LNQuaternion_SetFromAxis $57
#cmd LNMatrix $5A
#cmd LNMatrix_GetRow0 $3E5
#cmd LNMatrix_SetRow0 $3E7
#cmd LNMatrix_GetRow1 $3E8
#cmd LNMatrix_SetRow1 $3EA
#cmd LNMatrix_GetRow2 $3EB
#cmd LNMatrix_SetRow2 $3ED
#cmd LNMatrix_GetRow3 $3EE
#cmd LNMatrix_SetRow3 $3F0
#cmd LNMatrix_SetZeros $5F
#cmd LNMatrix_Set $60
#cmd LNColor $DA
#cmd LNColor_GetR $460
#cmd LNColor_SetR $462
#cmd LNColor_GetG $463
#cmd LNColor_SetG $465
#cmd LNColor_GetB $466
#cmd LNColor_SetB $468
#cmd LNColor_GetA $469
#cmd LNColor_SetA $46B
#cmd LNColor_SetZeros $DF
#cmd LNColor_Set $E0
#cmd LNPoint $E5
#cmd LNPoint_GetX $47F
#cmd LNPoint_SetX $481
#cmd LNPoint_GetY $482
#cmd LNPoint_SetY $484
#cmd LNPoint_SetZeros $E8
#cmd LNPoint_Set $E9
#cmd LNSize $EC
#cmd LNSize_GetWidth $48F
#cmd LNSize_SetWidth $491
#cmd LNSize_GetHeight $492
#cmd LNSize_SetHeight $494
#cmd LNSize_SetZeros $EF
#cmd LNSize_Set $F0
#cmd LNRect $F3
#cmd LNRect_GetX $49F
#cmd LNRect_SetX $4A1
#cmd LNRect_GetY $4A2
#cmd LNRect_SetY $4A4
#cmd LNRect_GetWidth $4A5
#cmd LNRect_SetWidth $4A7
#cmd LNRect_GetHeight $4A8
#cmd LNRect_SetHeight $4AA
#cmd LNRect_SetZeros $F8
#cmd LNRect_Set $F9
#cmd LNRect_GetLeft $FE
#cmd LNRect_SetSize $FF
#cmd LNRect_GetSize $101
#cmd LNThickness $102
#cmd LNThickness_GetLeft $4C3
#cmd LNThickness_SetLeft $4C5
#cmd LNThickness_GetTop $4C6
#cmd LNThickness_SetTop $4C8
#cmd LNThickness_GetRight $4C9
#cmd LNThickness_SetRight $4CB
#cmd LNThickness_GetBottom $4CC
#cmd LNThickness_SetBottom $4CE
#cmd LNThickness_SetZeros $107
#cmd LNThickness_Set $108

#cmd LNObject_Release $74
#cmd LNObject_Retain $75
#cmd LNObject_GetReferenceCount $76
#cmd LNObject_SetPrototype_OnSerialize $6AF
#cmd LNEventConnection_SetPrototype_OnSerialize $6BA
#cmd LNPromiseFailureDelegate_Create $40B
#cmd LNVariant_Create $7B
#cmd LNVariant_SetInt $7C
#cmd LNVariant_GetInt $7E
#cmd LNVariant_SetPrototype_OnSerialize $6C5
#cmd LNZVTestDelegate1_Create $414
#cmd LNZVTestDelegate2_Create $41A
#cmd LNZVTestDelegate3_Create $41F
#cmd LNZVTestEventHandler1_Create $424
#cmd LNZVTestEventHandler2_Create $429
#cmd LNZVTestPromise1_ThenWith $42C
#cmd LNZVTestPromise1_CatchWith $42E
#cmd LNZVTestPromise2_ThenWith $432
#cmd LNZVTestPromise2_CatchWith $434
#cmd LNZVTestClass1_Create $A7
#cmd LNZVTestClass1_SetTestDelegate1 $91
#cmd LNZVTestClass1_SetTestDelegate2 $93
#cmd LNZVTestClass1_SetTestDelegate3 $95
#cmd LNZVTestClass1_CallTestDelegate1 $97
#cmd LNZVTestClass1_CallTestDelegate2 $99
#cmd LNZVTestClass1_CallTestDelegate3 $9C
#cmd LNZVTestClass1_LoadAsync $9D
#cmd LNZVTestClass1_ExecuteAsync $9F
#cmd LNZVTestClass1_GetFilePath $A0
#cmd LNZVTestClass1_ConnectOnEvent1 $A1
#cmd LNZVTestClass1_RaiseEvent1 $A3
#cmd LNZVTestClass1_ConnectOnEvent2 $A4
#cmd LNZVTestClass1_RaiseEvent2 $A6
#cmd LNZVTestClass1_SetPrototype_OnSerialize $6D0
#cmd LNZVTestEventArgs1_Create $AA
#cmd LNZVTestEventArgs1_CreateWithValue $AB
#cmd LNZVTestEventArgs1_GetValue $A9
#cmd LNZVTestEventArgs1_SetPrototype_OnSerialize $6DB
#cmd LNSerializer2_SetPrototype_OnSerialize $6E6
#cmd LNAssetModel_Create $B7
#cmd LNAssetModel_Target $B6
#cmd LNAssetModel_SetPrototype_OnSerialize $6F1
#cmd LNAssets_SaveAssetToLocalFile $BA
#cmd LNAssets_LoadAssetFromLocalFile $BD
#cmd LNAssets_LoadAsset $BF
#cmd LNAssets_ReloadAsset $C1
#cmd LNTexture2DDelegate_Create $458
#cmd LNTexture2DPromise_ThenWith $45B
#cmd LNTexture2DPromise_CatchWith $45D
#cmd LNTexture_SetPrototype_OnSerialize $6FC
#cmd LNTexture2D_Create $113
#cmd LNTexture2D_CreateWithFormat $116
#cmd LNTexture2D_Load $10F
#cmd LNTexture2D_LoadEmoji $111
#cmd LNTexture2D_SetPrototype_OnSerialize $707
#cmd LNRenderView_SetPrototype_OnSerialize $712
#cmd LNSkinnedMeshModel_Load $122
#cmd LNSkinnedMeshModel_GetAnimationController $124
#cmd LNSkinnedMeshModel_SetPrototype_OnSerialize $71D
#cmd LNAnimationController_AddClip $126
#cmd LNAnimationController_Play $128
#cmd LNAnimationController_SetPrototype_OnSerialize $728
#cmd LNCollisionShape_SetPrototype_OnSerialize $733
#cmd LNBoxCollisionShape_Create $12D
#cmd LNBoxCollisionShape_CreateWHD $12F
#cmd LNBoxCollisionShape_SetPrototype_OnSerialize $73E
#cmd LNAnimationClip_Load $134
#cmd LNAnimationClip_SetPrototype_OnSerialize $749
#cmd LNAnimationState_SetPrototype_OnSerialize $754
#cmd LNComponent_SetPrototype_OnSerialize $75F
#cmd LNVisualComponent_SetVisible $139
#cmd LNVisualComponent_IsVisible $13B
#cmd LNVisualComponent_SetPrototype_OnSerialize $76A
#cmd LNSpriteComponent_SetTexture $13D
#cmd LNSpriteComponent_SetPrototype_OnSerialize $775
#cmd LNCollisionEventHandler_Create $4F9
#cmd LNCharacterController_Create $15A
#cmd LNCharacterController_SetVelocity $147
#cmd LNCharacterController_GetVelocity $149
#cmd LNCharacterController_SetInputControlEnabled $14A
#cmd LNCharacterController_SetCameraControlEnabled $14C
#cmd LNCharacterController_SetHeight $14E
#cmd LNCharacterController_GetHeight $150
#cmd LNCharacterController_SetCameraRadius $151
#cmd LNCharacterController_GetCameraRadius $153
#cmd LNCharacterController_SetCollisionEnter $154
#cmd LNCharacterController_SetCollisionLeave $156
#cmd LNCharacterController_SetCollisionStay $158
#cmd LNCharacterController_SetPrototype_OnSerialize $780
#cmd LNWorld_Add $15C
#cmd LNWorld_SetPrototype_OnSerialize $78B
#cmd LNComponentList_GetLength $514
#cmd LNComponentList_GetItem $516
#cmd LNComponentList_SetPrototype_OnSerialize $796
#cmd LNWorldObject_Create $192
#cmd LNWorldObject_SetPosition $160
#cmd LNWorldObject_SetPositionXYZ $162
#cmd LNWorldObject_GetPosition $166
#cmd LNWorldObject_SetRotationQuaternion $167
#cmd LNWorldObject_SetRotation $169
#cmd LNWorldObject_GetRotation $16D
#cmd LNWorldObject_SetScale $16E
#cmd LNWorldObject_SetScaleS $170
#cmd LNWorldObject_SetScaleXYZ $172
#cmd LNWorldObject_GetScale $176
#cmd LNWorldObject_SetCenterPoint $177
#cmd LNWorldObject_SetCenterPointXYZ $179
#cmd LNWorldObject_GetCenterPoint $17D
#cmd LNWorldObject_LookAt $17E
#cmd LNWorldObject_LookAtXYZ $180
#cmd LNWorldObject_AddComponent $184
#cmd LNWorldObject_RemoveComponent $186
#cmd LNWorldObject_AddTag $188
#cmd LNWorldObject_RemoveTag $18A
#cmd LNWorldObject_HasTag $18C
#cmd LNWorldObject_Destroy $18E
#cmd LNWorldObject_GetComponents $18F
#cmd LNWorldObject_SetPrototype_OnSerialize $7A1
#cmd LNWorldObject_SetPrototype_OnUpdate $7AC
#cmd LNVisualObject_SetVisible $194
#cmd LNVisualObject_IsVisible $196
#cmd LNVisualObject_SetPrototype_OnSerialize $7B7
#cmd LNVisualObject_SetPrototype_OnUpdate $7C2
#cmd LNCamera_SetPrototype_OnSerialize $7CD
#cmd LNCamera_SetPrototype_OnUpdate $7D8
#cmd LNEnvironmentLight_SetEnabled $199
#cmd LNEnvironmentLight_IsEnabled $19B
#cmd LNEnvironmentLight_SetColor $19C
#cmd LNEnvironmentLight_GetColor $19E
#cmd LNEnvironmentLight_SetAmbientColor $19F
#cmd LNEnvironmentLight_GetAmbientColor $1A1
#cmd LNEnvironmentLight_GetSkyColor $1A2
#cmd LNEnvironmentLight_SetSkyColor $1A3
#cmd LNEnvironmentLight_GetGroundColor $1A5
#cmd LNEnvironmentLight_SetGroundColor $1A6
#cmd LNEnvironmentLight_SetIntensity $1A8
#cmd LNEnvironmentLight_GetIntensity $1AA
#cmd LNEnvironmentLight_SetShadowEffectiveDistance $1AB
#cmd LNEnvironmentLight_GetShadowEffectiveDistance $1AD
#cmd LNEnvironmentLight_SetShadowEffectiveDepth $1AE
#cmd LNEnvironmentLight_GetShadowEffectiveDepth $1B0
#cmd LNEnvironmentLight_SetPrototype_OnSerialize $7E3
#cmd LNEnvironmentLight_SetPrototype_OnUpdate $7EE
#cmd LNDirectionalLight_Create $1C1
#cmd LNDirectionalLight_CreateWithColor $1C2
#cmd LNDirectionalLight_SetEnabled $1B2
#cmd LNDirectionalLight_IsEnabled $1B4
#cmd LNDirectionalLight_SetColor $1B5
#cmd LNDirectionalLight_GetColor $1B7
#cmd LNDirectionalLight_SetIntensity $1B8
#cmd LNDirectionalLight_GetIntensity $1BA
#cmd LNDirectionalLight_SetShadowEffectiveDistance $1BB
#cmd LNDirectionalLight_GetShadowEffectiveDistance $1BD
#cmd LNDirectionalLight_SetShadowEffectiveDepth $1BE
#cmd LNDirectionalLight_GetShadowEffectiveDepth $1C0
#cmd LNDirectionalLight_SetPrototype_OnSerialize $7F9
#cmd LNDirectionalLight_SetPrototype_OnUpdate $804
#cmd LNPointLight_Create $1D4
#cmd LNPointLight_CreateWithColorAndRange $1D5
#cmd LNPointLight_SetEnabled $1C5
#cmd LNPointLight_IsEnabled $1C7
#cmd LNPointLight_SetColor $1C8
#cmd LNPointLight_GetColor $1CA
#cmd LNPointLight_SetIntensity $1CB
#cmd LNPointLight_GetIntensity $1CD
#cmd LNPointLight_SetRange $1CE
#cmd LNPointLight_GetRange $1D0
#cmd LNPointLight_SetAttenuation $1D1
#cmd LNPointLight_GetAttenuation $1D3
#cmd LNPointLight_SetPrototype_OnSerialize $80F
#cmd LNPointLight_SetPrototype_OnUpdate $81A
#cmd LNSpotLight_Create $1EE
#cmd LNSpotLight_CreateWithColorAndRange $1EF
#cmd LNSpotLight_SetEnabled $1D9
#cmd LNSpotLight_IsEnabled $1DB
#cmd LNSpotLight_SetColor $1DC
#cmd LNSpotLight_GetColor $1DE
#cmd LNSpotLight_SetIntensity $1DF
#cmd LNSpotLight_GetIntensity $1E1
#cmd LNSpotLight_SetRange $1E2
#cmd LNSpotLight_GetRange $1E4
#cmd LNSpotLight_SetAttenuation $1E5
#cmd LNSpotLight_GetAttenuation $1E7
#cmd LNSpotLight_SetAngle $1E8
#cmd LNSpotLight_GetAngle $1EA
#cmd LNSpotLight_SetPenumbra $1EB
#cmd LNSpotLight_GetPenumbra $1ED
#cmd LNSpotLight_SetPrototype_OnSerialize $825
#cmd LNSpotLight_SetPrototype_OnUpdate $830
#cmd LNTestDelegate_Create $5BA
#cmd LNSprite_Create $205
#cmd LNSprite_CreateWithTexture $206
#cmd LNSprite_CreateWithTextureAndSize $208
#cmd LNSprite_SetTexture $1F7
#cmd LNSprite_SetSize $1F9
#cmd LNSprite_SetSizeWH $1FB
#cmd LNSprite_SetSourceRectXYWH $1FE
#cmd LNSprite_SetCallerTest $203
#cmd LNSprite_SetPrototype_OnSerialize $83B
#cmd LNSprite_SetPrototype_OnUpdate $846
#cmd LNCameraOrbitControlComponent_Create $20D
#cmd LNCameraOrbitControlComponent_SetPrototype_OnSerialize $851
#cmd LNRaycaster_FromScreen $20F
#cmd LNRaycaster_IntersectPlane $211
#cmd LNRaycaster_SetPrototype_OnSerialize $85C
#cmd LNRaycastResult_GetPoint $216
#cmd LNRaycastResult_SetPrototype_OnSerialize $867
#cmd LNWorldRenderView_SetGuideGridEnabled $218
#cmd LNWorldRenderView_GetGuideGridEnabled $21A
#cmd LNWorldRenderView_SetPrototype_OnSerialize $872
#cmd LNBoxMesh_Create $21C
#cmd LNBoxMesh_SetPrototype_OnSerialize $87D
#cmd LNBoxMesh_SetPrototype_OnUpdate $888
#cmd LNPlaneMesh_Create $21E
#cmd LNPlaneMesh_SetPrototype_OnSerialize $893
#cmd LNPlaneMesh_SetPrototype_OnUpdate $89E
#cmd LNStaticMesh_Load $220
#cmd LNStaticMesh_MakeCollisionBody $222
#cmd LNStaticMesh_SetPrototype_OnSerialize $8A9
#cmd LNStaticMesh_SetPrototype_OnUpdate $8B4
#cmd LNSkinnedMeshComponent_Create $227
#cmd LNSkinnedMeshComponent_SetModel $225
#cmd LNSkinnedMeshComponent_SetPrototype_OnSerialize $8BF
#cmd LNCollision_GetWorldObject $229
#cmd LNCollision_SetPrototype_OnSerialize $8CA
#cmd LNTriggerBodyComponent_Create $22D
#cmd LNTriggerBodyComponent_AddCollisionShape $22B
#cmd LNTriggerBodyComponent_SetPrototype_OnSerialize $8D5
#cmd LNScene_SetClearMode $22F
#cmd LNScene_SetSkyColor $231
#cmd LNScene_SetSkyHorizonColor $233
#cmd LNScene_SetSkyCloudColor $235
#cmd LNScene_SetSkyOverlayColor $237
#cmd LNScene_GotoLevel $239
#cmd LNScene_CallLevel $23C
#cmd LNScene_ReturnLevel $23F
#cmd LNScene_ActiveLevel $241
#cmd LNScene_IsTransitionEffectRunning $242
#cmd LNScene_SetTransitionEffectMode $243
#cmd LNScene_TransitionEffectMode $245
#cmd LNScene_SetTransitionDuration $246
#cmd LNScene_TransitionDuration $248
#cmd LNScene_SetTransitionEffectColor $249
#cmd LNScene_TransitionEffectColor $24B
#cmd LNScene_SetTransitionEffectMaskTexture $24C
#cmd LNScene_TransitionEffectMaskTexture $24E
#cmd LNScene_SetTransitionEffectVague $24F
#cmd LNScene_TransitionEffectVague $251
#cmd LNScene_StartFadeOut $252
#cmd LNScene_StartFadeIn $253
#cmd LNScene_SetScreenBlendColor $254
#cmd LNScene_ScreenBlendColor $256
#cmd LNLevel_Create $266
#cmd LNLevel_AddObject $258
#cmd LNLevel_RemoveObject $25A
#cmd LNLevel_AddSubLevel $25C
#cmd LNLevel_RemoveSubLevel $25E
#cmd LNLevel_RemoveAllSubLevels $260
#cmd LNLevel_SetPrototype_OnSerialize $8E0
#cmd LNLevel_SetPrototype_OnStart $8EB
#cmd LNLevel_SetPrototype_OnStop $8F6
#cmd LNLevel_SetPrototype_OnPause $901
#cmd LNLevel_SetPrototype_OnResume $90C
#cmd LNLevel_SetPrototype_OnUpdate $917
#cmd LNUIEventArgs_Sender $26D
#cmd LNUIEventArgs_SetPrototype_OnSerialize $922
#cmd LNUIGeneralEventHandler_Create $5F8
#cmd LNUIEventHandler_Create $5FD
#cmd LNUILayoutElement_SetPrototype_OnSerialize $92D
#cmd LNUIElement_SetSize $27F
#cmd LNUIElement_SetSizeWH $281
#cmd LNUIElement_SetMargin $284
#cmd LNUIElement_GetMargin $286
#cmd LNUIElement_SetPadding $287
#cmd LNUIElement_GetPadding $289
#cmd LNUIElement_SetHAlignment $28A
#cmd LNUIElement_GetHAlignment $28C
#cmd LNUIElement_SetVAlignment $28D
#cmd LNUIElement_GetVAlignment $28F
#cmd LNUIElement_SetAlignments $290
#cmd LNUIElement_SetPosition $293
#cmd LNUIElement_SetPositionXYZ $295
#cmd LNUIElement_GetPosition $299
#cmd LNUIElement_SetRotation $29A
#cmd LNUIElement_SetEulerAngles $29C
#cmd LNUIElement_GetRotation $2A0
#cmd LNUIElement_SetScale $2A1
#cmd LNUIElement_SetScaleS $2A3
#cmd LNUIElement_SetScaleXY $2A5
#cmd LNUIElement_GetScale $2A8
#cmd LNUIElement_SetCenterPoint $2A9
#cmd LNUIElement_SetCenterPointXYZ $2AB
#cmd LNUIElement_GetCenterPoint $2AF
#cmd LNUIElement_SetEnabled $2B0
#cmd LNUIElement_IsEnabled $2B2
#cmd LNUIElement_SetData $2B3
#cmd LNUIElement_GetData $2B5
#cmd LNUIElement_AddChild $2B6
#cmd LNUIElement_SetPrototype_OnSerialize $938
#cmd LNUITextBlock_Create $2B9
#cmd LNUITextBlock_CreateWithText $2BA
#cmd LNUITextBlock_SetPrototype_OnSerialize $943
#cmd LNUISprite_Create $2C7
#cmd LNUISprite_CreateWithTexture $2C8
#cmd LNUISprite_SetTexture $2BD
#cmd LNUISprite_SetSourceRect $2BF
#cmd LNUISprite_SetSourceRectXYWH $2C1
#cmd LNUISprite_GetSourceRect $2C6
#cmd LNUISprite_SetPrototype_OnSerialize $94E
#cmd LNUIIcon_LoadFontIcon $2CB
#cmd LNUIIcon_LoadFontIconWithNameSize $2CD
#cmd LNUIIcon_LoadFontIconWithNameSizeColor $2D0
#cmd LNUIIcon_SetPrototype_OnSerialize $959
#cmd LNUI_Add $2D5
#cmd LNUI_Remove $2D7
#cmd LNUILayoutPanel_SetPrototype_OnSerialize $964
#cmd LNUIBoxLayout_Create $2DE
#cmd LNUIBoxLayout_SetOrientation $2DB
#cmd LNUIBoxLayout_GetOrientation $2DD
#cmd LNUIBoxLayout_SetPrototype_OnSerialize $96F
#cmd LNUIGridLayout_Create $2EE
#cmd LNUIGridLayout_SetColumnCount $2E0
#cmd LNUIGridLayout_SetRow $2E2
#cmd LNUIGridLayout_SetColumn $2E5
#cmd LNUIGridLayout_SetPlacement $2E8
#cmd LNUIGridLayout_SetPrototype_OnSerialize $97A
#cmd LNUIControl_SetPrototype_OnSerialize $985
#cmd LNUIButtonBase_SetText $2F1
#cmd LNUIButtonBase_SetPrototype_OnSerialize $990
#cmd LNUIButton_Create $2F4
#cmd LNUIButton_CreateWithText $2F5
#cmd LNUIButton_ConnectOnClicked $2F7
#cmd LNUIButton_SetPrototype_OnSerialize $99B
#cmd LNUIWindow_Create $2FA
#cmd LNUIWindow_SetPrototype_OnSerialize $9A6
#cmd LNUIListItem_ConnectOnSubmit $2FF
#cmd LNUIListItem_SetPrototype_OnSerialize $9B1
#cmd LNUIListItemsControl_SetItemsLayoutPanel $302
#cmd LNUIListItemsControl_SetSubmitMode $304
#cmd LNUIListItemsControl_GetSubmitMode $306
#cmd LNUIListItemsControl_SetPrototype_OnSerialize $9BC
#cmd LNUIListBoxItem_Create $308
#cmd LNUIListBoxItem_SetPrototype_OnSerialize $9C7
#cmd LNUIListBox_Create $30D
#cmd LNUIListBox_AddItem $30B
#cmd LNUIListBox_SetPrototype_OnSerialize $9D2
#cmd LNInput_IsPressed $30F
#cmd LNInput_IsTriggered $311
#cmd LNInput_IsTriggeredOff $313
#cmd LNInput_IsRepeated $315
#cmd LNInput_GetAxisValue $317
#cmd LNInput_ClearAllBindings $319
#cmd LNMouse_Pressed $31B
#cmd LNMouse_Triggered $31D
#cmd LNMouse_TriggeredOff $31F
#cmd LNMouse_Repeated $321
#cmd LNMouse_Position $323
#cmd LNInterpreterCommand_Code $325
#cmd LNInterpreterCommand_ParamsCount $326
#cmd LNInterpreterCommand_Param $327
#cmd LNInterpreterCommand_SetPrototype_OnSerialize $9DD
#cmd LNInterpreterCommandList_Create $33E
#cmd LNInterpreterCommandList_AddCommand $32A
#cmd LNInterpreterCommandList_AddCommand1 $32C
#cmd LNInterpreterCommandList_AddCommand2 $32F
#cmd LNInterpreterCommandList_AddCommand3 $333
#cmd LNInterpreterCommandList_AddCommand4 $338
#cmd LNInterpreterCommandList_SetPrototype_OnSerialize $9E8
#cmd LNInterpreterCommandDelegate_Create $681
#cmd LNInterpreter_Create $352
#cmd LNInterpreter_Clear $343
#cmd LNInterpreter_Run $344
#cmd LNInterpreter_IsRunning $346
#cmd LNInterpreter_Update $347
#cmd LNInterpreter_Terminate $348
#cmd LNInterpreter_RegisterCommandHandler $349
#cmd LNInterpreter_SetWaitMode $34C
#cmd LNInterpreter_GetWaitMode $34E
#cmd LNInterpreter_SetWaitCount $34F
#cmd LNInterpreter_GetWaitCount $351
#cmd LNInterpreter_SetPrototype_OnSerialize $9F3
#cmd LNInterpreter_SetPrototype_OnUpdateWait $9FF
#cmd LNEngineSettings_SetMainWindowSize $355
#cmd LNEngineSettings_SetMainWorldViewSize $358
#cmd LNEngineSettings_SetMainWindowTitle $35B
#cmd LNEngineSettings_AddAssetDirectory $35D
#cmd LNEngineSettings_AddAssetArchive $35F
#cmd LNEngineSettings_SetFrameRate $362
#cmd LNEngineSettings_SetDefaultUITheme $364
#cmd LNEngineSettings_SetDebugToolEnabled $366
#cmd LNEngineSettings_SetEngineLogEnabled $368
#cmd LNEngineSettings_SetEngineLogFilePath $36A
#cmd LNEngine_Initialize $36D
#cmd LNEngine_Finalize $36E
#cmd LNEngine_Update $36F
#cmd LNEngine_Run $370
#cmd LNEngine_Time $372
#cmd LNEngine_GetCamera $373
#cmd LNEngine_GetMainLight $374
#cmd LNEngine_GetRenderView $375
#cmd LNApplication_Create $37A
#cmd LNApplication_OnInit $377
#cmd LNApplication_OnUpdate $378
#cmd LNApplication_World $379
#cmd LNApplication_SetPrototype_OnSerialize $A0A
#cmd LNApplication_SetPrototype_OnInit $A15
#cmd LNApplication_SetPrototype_OnUpdate $A20
#cmd LNDebug_SetGuideGridEnabled $37C
#cmd LNDebug_SetPhysicsDebugDrawEnabled $37E
#cmd LNDebug_Print $380
#cmd LNDebug_PrintWithTime $382
#cmd LNDebug_PrintWithTimeAndColor $385
#cmd LNObjectSerializeHandler_Create $6AD
#cmd LNEventConnectionSerializeHandler_Create $6B8
#cmd LNVariantSerializeHandler_Create $6C3
#cmd LNZVTestClass1SerializeHandler_Create $6CE
#cmd LNZVTestEventArgs1SerializeHandler_Create $6D9
#cmd LNSerializer2SerializeHandler_Create $6E4
#cmd LNAssetModelSerializeHandler_Create $6EF
#cmd LNTextureSerializeHandler_Create $6FA
#cmd LNTexture2DSerializeHandler_Create $705
#cmd LNRenderViewSerializeHandler_Create $710
#cmd LNSkinnedMeshModelSerializeHandler_Create $71B
#cmd LNAnimationControllerSerializeHandler_Create $726
#cmd LNCollisionShapeSerializeHandler_Create $731
#cmd LNBoxCollisionShapeSerializeHandler_Create $73C
#cmd LNAnimationClipSerializeHandler_Create $747
#cmd LNAnimationStateSerializeHandler_Create $752
#cmd LNComponentSerializeHandler_Create $75D
#cmd LNVisualComponentSerializeHandler_Create $768
#cmd LNSpriteComponentSerializeHandler_Create $773
#cmd LNCharacterControllerSerializeHandler_Create $77E
#cmd LNWorldSerializeHandler_Create $789
#cmd LNComponentListSerializeHandler_Create $794
#cmd LNWorldObjectSerializeHandler_Create $79F
#cmd LNWorldObjectUpdateHandler_Create $7AA
#cmd LNVisualObjectSerializeHandler_Create $7B5
#cmd LNVisualObjectUpdateHandler_Create $7C0
#cmd LNCameraSerializeHandler_Create $7CB
#cmd LNCameraUpdateHandler_Create $7D6
#cmd LNEnvironmentLightSerializeHandler_Create $7E1
#cmd LNEnvironmentLightUpdateHandler_Create $7EC
#cmd LNDirectionalLightSerializeHandler_Create $7F7
#cmd LNDirectionalLightUpdateHandler_Create $802
#cmd LNPointLightSerializeHandler_Create $80D
#cmd LNPointLightUpdateHandler_Create $818
#cmd LNSpotLightSerializeHandler_Create $823
#cmd LNSpotLightUpdateHandler_Create $82E
#cmd LNSpriteSerializeHandler_Create $839
#cmd LNSpriteUpdateHandler_Create $844
#cmd LNCameraOrbitControlComponentSerializeHandler_Create $84F
#cmd LNRaycasterSerializeHandler_Create $85A
#cmd LNRaycastResultSerializeHandler_Create $865
#cmd LNWorldRenderViewSerializeHandler_Create $870
#cmd LNBoxMeshSerializeHandler_Create $87B
#cmd LNBoxMeshUpdateHandler_Create $886
#cmd LNPlaneMeshSerializeHandler_Create $891
#cmd LNPlaneMeshUpdateHandler_Create $89C
#cmd LNStaticMeshSerializeHandler_Create $8A7
#cmd LNStaticMeshUpdateHandler_Create $8B2
#cmd LNSkinnedMeshComponentSerializeHandler_Create $8BD
#cmd LNCollisionSerializeHandler_Create $8C8
#cmd LNTriggerBodyComponentSerializeHandler_Create $8D3
#cmd LNLevelSerializeHandler_Create $8DE
#cmd LNLevelStartHandler_Create $8E9
#cmd LNLevelStopHandler_Create $8F4
#cmd LNLevelPauseHandler_Create $8FF
#cmd LNLevelResumeHandler_Create $90A
#cmd LNLevelUpdateHandler_Create $915
#cmd LNUIEventArgsSerializeHandler_Create $920
#cmd LNUILayoutElementSerializeHandler_Create $92B
#cmd LNUIElementSerializeHandler_Create $936
#cmd LNUITextBlockSerializeHandler_Create $941
#cmd LNUISpriteSerializeHandler_Create $94C
#cmd LNUIIconSerializeHandler_Create $957
#cmd LNUILayoutPanelSerializeHandler_Create $962
#cmd LNUIBoxLayoutSerializeHandler_Create $96D
#cmd LNUIGridLayoutSerializeHandler_Create $978
#cmd LNUIControlSerializeHandler_Create $983
#cmd LNUIButtonBaseSerializeHandler_Create $98E
#cmd LNUIButtonSerializeHandler_Create $999
#cmd LNUIWindowSerializeHandler_Create $9A4
#cmd LNUIListItemSerializeHandler_Create $9AF
#cmd LNUIListItemsControlSerializeHandler_Create $9BA
#cmd LNUIListBoxItemSerializeHandler_Create $9C5
#cmd LNUIListBoxSerializeHandler_Create $9D0
#cmd LNInterpreterCommandSerializeHandler_Create $9DB
#cmd LNInterpreterCommandListSerializeHandler_Create $9E6
#cmd LNInterpreterSerializeHandler_Create $9F1
#cmd LNInterpreterUpdateWaitHandler_Create $9FD
#cmd LNApplicationSerializeHandler_Create $A08
#cmd LNApplicationInitHandler_Create $A13
#cmd LNApplicationUpdateHandler_Create $A1E



#cmd ln_args $1
#cmd ln_set_args $2

#endif // __lumino__
