
find_package(toml11 CONFIG REQUIRED)
find_package(Vorbis CONFIG REQUIRED)
find_package(Bullet CONFIG REQUIRED)
find_package(box2d CONFIG REQUIRED)
find_path(STB_INCLUDE_DIRS "stb_image.h")
find_path(TINYGLTF_INCLUDE_DIRS "tiny_gltf.h")
find_package(imgui CONFIG REQUIRED)

if (LN_OS_DESKTOP)
    find_package(GTest CONFIG REQUIRED)
    find_package(OpenAL CONFIG REQUIRED)
    find_package(glfw3 CONFIG REQUIRED)
    find_package(glad CONFIG REQUIRED)
    find_path(VULKAN_HEADERS_INCLUDE_DIRS "vulkan/vk_icd.h")
endif()
