
find_package(yaml-cpp CONFIG REQUIRED)

#if (NOT DEFINED EMSCRIPTEN)
#    find_package(CURL CONFIG REQUIRED)
#endif()

if (LN_OS_DESKTOP)
    find_package(glfw3 CONFIG REQUIRED)
    find_package(glad CONFIG REQUIRED)
endif()

if (LN_OS_DESKTOP)
    find_package(VulkanHeaders CONFIG REQUIRED)
    find_package(glslang CONFIG REQUIRED)
    #find_package(spirv_cross_c CONFIG REQUIRED)
    find_package(spirv_cross_core CONFIG REQUIRED)
    #find_package(spirv_cross_cpp CONFIG REQUIRED)
    find_package(spirv_cross_glsl CONFIG REQUIRED)
    find_package(spirv_cross_hlsl CONFIG REQUIRED)
    find_package(spirv_cross_msl CONFIG REQUIRED)
    find_package(spirv_cross_reflect CONFIG REQUIRED)
    find_package(spirv_cross_util CONFIG REQUIRED)
endif()

find_package(ZLIB REQUIRED)
find_package(libpng CONFIG REQUIRED)
find_package(nanovg CONFIG REQUIRED)
find_package(freetype CONFIG REQUIRED)
find_package(tinyobjloader CONFIG REQUIRED)
