require "bundler/gem_tasks"
require 'rake/testtask'
require "rake/extensiontask"
require 'yard'
require 'yard/rake/yardoc_task'
require "fileutils"
task :default => :spec

Rake::TestTask.new do |t|
  t.test_files = FileList['test/test_*.rb'].exclude('test/test_assoccoords.rb')
end

Rake::ExtensionTask.new "Lumino_RubyExt" do |ext|
  # copy dll
  lib = File.expand_path("../../../../../build/MSVC2017-x64-MT/src/LuminoEngine/Release/LuminoEngine.dll", __FILE__)
  to = "ext/LuminoEngine.dll"
  FileUtils.cp(lib, to)
  p "Lib copy (" + lib + ", " + to + ")"

  # copy assets
  noto_emoji = File.expand_path("../../../../../tools/EngineAssets", __FILE__)
  FileUtils.cp_r(noto_emoji, "ext")
  p "Copied EngineAssets."

  ext.lib_dir = "lib/lumino"
end

FILES = ['app/controllers/**/*.rb',
              'app/helpers/**/*.rb', 
              'app/mailers/**/*.rb', 
              'app/models/**/*.rb']
OPTIONS = ['--debug', '--verbose']
YARD::Rake::YardocTask.new do |t|
  t.files   = ['Lumino.RubyYARDOCSource.generated.rb']
  if Rake.application.options.trace
    t.options = ['--debug', '--verbose']
  end
end

