name: github pages

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Build
      uses: nikeee/docfx-action@master
      with:
        args: docs/WebDocument/docfx.json

    - name: Deploy
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: docs/WebDocument/_site
        GH_PAT: ${{ secrets.CI_PUSH_TOKEN }}
